### ISSUE TITLE
Add an offset to ArrayHistogram

### ISSUE THREAD

**Issue by non** [geotrellis/geotrellis#1]
Currently ArrayHistogram maps values directly as array indices. It would be good to add an offset parameter to modify this addressing, so that if you have data ranging from e.g. 145-316 you won't end up wasting the first 145 buckets of the histogram.

The offset can default to 0 to preserve the existing behavior. Operations involving ArrayHistogram should also be changed.

**Comment by lossyrob** [comment]
Closing, as ArrayHistogram has been removed.
