### ISSUE TITLE
Resolve issue of gridBounds in RasterMetaData

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1017]
If we call `.gridBounds` on a `RasterMetaData`, the extent of the raster should snap to the tileLayout grid. Since the right and lower edge of the extent are considered to be part of the top or left part of additional tiles, the grid bounds are actually one more in that direction then that should be. I believe this is a bug with the mapTransform...we should only be inclusive as far as boarders go with the top and left borders of tile cells and extents (which is how we've done it in geotrellis.raster).

**Comment by echeipesh** [comment]
I would add to this that `RasterMetaData` should not have `.extent` field, which represented the extent of the pixels ingested. The only extent that should be associated with a tiled raster is the extent of the `.tileLayout`.

**Comment by echeipesh** [comment]
After recent discussion it has been decided that `extent` field on `RasterMetaData` class is specifically the extent of data cells, not the tiles. This behavior is needed for the Buffered Retroject to work correctly.
