### ISSUE TITLE
BigTiff support for Ingest

### ISSUE THREAD

**Issue by mfsny** [geotrellis/geotrellis#1055]
Very nice project. Are there any plans to include support for BigTIFF format in the future releases? 
Regards,
Slavo

**Comment by lossyrob** [comment]
Hi Slavo, we generally avoid working with single large files, since the aim of this project is to lean on distributed process (which you can't do with one giant file). One thing would be to support the ingest of BigTIFF, which we might already be able to do with our GDAL bindings project. What is the use case for BibTIFF that you're interested in?

**Comment by pibe81** [comment]
I would also be interested in the support of BigTIFF. I agree that we shouldn't have giant files, but I for instance have a vendor that provides us with geoTIFF files that are about 200MB, but are still encoded as BigTIFF. My use case is quite standard, I would like to show on a map (say Germany) different KPIs encoded as raster (cost of household, cost of groceries, cost of transportation, ...) and do geoalgebra with these.
If you could also suggest some effective way to convert BigTIFF into GeoTIFF it would be great. I tried with QuantumGIS, but it just explodes when trying to re-export the TIF.

**Comment by mfsny** [comment]
Our use case is based on files with natural catastrophes data. The data provider is sending us GeoTIFFs in BigTIFF format. We are currently in the process of clarifying, if these could be converted to simple TIFF, but of course, we would prefer support for BigTIFF by geotrellis directly so that no conversion is required.
The use case itself is "standard". Have a repository of geodata, allow data scientists to do some map algebra on these and display the results in a web app. That is why geotrellis looks so attractive to us.

**Comment by fosskers** [comment]
Related to #1627 .

**Comment by jbouffard** [comment]
@mfsny @pliguori We now support BigTiff reading! The process of ingesting BigTiffs is the same as normal Tiffs, so you won't have to change any of your existing code.
