### ISSUE TITLE
LatLng to WebMercator reprojection producing NaN value

### ISSUE THREAD

**Issue by jafaeldon** [geotrellis/geotrellis#1094]
**Geotrellis version**: 0.10-SNAPSHOT
**Scala version**: 2.10.5
**Java version**: 1.7

Reprojecting from a valid LatLng to WebMercator causes NaN for certain locations.

Sample code to reproduce:

```scala
// Sample location in the philippines
val poly = """{"type":"Feature","properties":"","geometry":{"type":"Polygon","coordinates":[[[14.664806348190549,121.08839035034178],[14.630261223447867,121.11122131347655],[14.635908394791587,121.07517242431639]]]}}"""
val reprojectedPoly = poly.parseGeoJson[PolygonFeature[String]].reproject(LatLng, WebMercator)
```

Causes the following exception:

```
java.lang.RuntimeException: Cannot create a polygon with unclosed exterior: LINESTRING (1632478.7752625376 NaN, 1628633.229566792 NaN, 1629261.8698051975 NaN, 1632478.7752625376 NaN)
        at scala.sys.package$.error(package.scala:27)
        at geotrellis.vector.Polygon$.apply(Polygon.scala:37)
        at geotrellis.vector.reproject.package$Reproject$.apply(package.scala:41)
        at geotrellis.vector.reproject.package$Reproject$.apply(package.scala:38)
        at geotrellis.vector.reproject.package$Reproject$.apply(package.scala:55)
        at geotrellis.vector.reproject.package$ReprojectPolygonFeature.reproject(package.scala:191)
        ...
```

The NaN was produced from [MercatorProjection.java](https://github.com/geotrellis/geotrellis/blob/master/proj4/src/main/java/org/osgeo/proj4j/proj/MercatorProjection.java) at line 35: 

```scala
public ProjCoordinate project(double lam, double phi, ProjCoordinate out) {
		if (spherical) {
			out.x = scaleFactor * lam;
			out.y = scaleFactor * Math.log(Math.tan(ProjectionMath.QUARTERPI + 0.5 * phi)); // Error here at line 35: Math.log('negative number') = NaN
		} else {
			out.x = scaleFactor * lam;
			out.y = -scaleFactor * Math.log(ProjectionMath.tsfn(phi, Math.sin(phi), e));
		}
		return out;
	}
```

**Comment by jafaeldon** [comment]
If I try to switch the input lat and lon (i.e put lon first before the lat) it appears to give the correct values.

**Comment by jafaeldon** [comment]
It appears the order of LatLng values should be longitude first before latitude. Might be a good idea to use LngLat instead to avoid the confusion. Closing this issue.

**Comment by lossyrob** [comment]
Hi James,

Sorry you got stuck on that, the lat long <-> long lat problem always comes up. I've been bitten by it many times (not in GeoTrellis per say, but things like Leaflet).

We use Proj4j under the covers, and proj4 strings name that projection as `latlon`, so we were kind of piggybacking on that order choice (http://proj.maptools.org/faq.html).

Thanks,
Rob
