### ISSUE TITLE
Alternative Geo Implementations for Cassandra

### ISSUE THREAD

**Issue by allixender** [geotrellis/geotrellis#1098]
**GSoc2015 GeoTrellis Cassandra tracker for shared scratch documentation**

"Research" indicates, it is possible to add native geo-indexing capabilities to Cassandra. A couple of main leads to follow up:

- 2011 SimpleGeo did already work on stuff
  - Geo Meetup http://www.meetup.com/geomeetup/events/17034143/
  - and the slides of the presentation: https://dl.dropboxusercontent.com/u/4779803/geo_to_cassandra.pdf
  - Cloudstock presentation: https://www.youtube.com/watch?v=7J61pPG9j90&hd=1
  - presenting kd-tree data structure, I haven't fully understood the data model yet, but it keeps additional index and index-meta data tables to build the trees, with on of the values pointing back to a primary cassandra index (presumably the actual hereby geo-referencing data item)
  - they got acquired end of 2011 and directly shut down in 2012 by Urban Airship
  - even their twitter stream ended then https://twitter.com/simplegeo
  - left overs GitHub repo, only clients it seems ... https://github.com/simplegeo
  - http://readwrite.com/2011/10/31/startup_shocker_simplegeo_gets_acquired_by_urbanai
  - http://techcrunch.com/2012/01/12/urban-airship-to-shutter-simplegeo-services-in-march-with-factual-picking-up-the-slack/

- another approach is a custom secondary index as described here:
  - https://issues.apache.org/jira/browse/CASSANDRA-6480
  - main examples include Lucene indexing
  - Stargate https://github.com/tuplejump/stargate-core
  - Lucene by the way also now (with v4.0 in 2012 or so) supports basic geo-indexing, now at v5.1 https://lucene.apache.org/core/5_1_0/spatial/index.html
  - Lucene nowadays works apparently with Spatial4J, Why not use JTS? Why should you use Spatial4j? ... https://github.com/spatial4j/spatial4j
  - the use of "external" Java classes for Cassandra indexing is nicely explained in Stargate docs: http://stargate-core.readthedocs.org/en/latest/quickstart.html
  - I assume, as typical with Lucene, it will use its own index directory outside of the Cassandra database realm (meaning not using other cassandra tables as SimpleGeo did)

**Comment by allixender** [comment]
Update:

I tweeted Mike Malone, the engineer from SimpleGeo who presented on kd-tress with Cassandra. Maybe he has some more info. I am roughly understanding the concept, but I have no idea yet, how to approach a kd-trees indexing for GeoTrellis. Seemed that SimpleGeo was 'only' indexing points, where we ideally index polygons.

I tried to compile tuple jump stargate-core. against the last retrievable Cassandra versions, which would be **2.0.15**. Stargate-core is tested up to Cassandra version **2.0.11** and can be compiled up to version **2.0.14**.

When trying to compile against **2.0.15** the build fails do to changed mehtod signature etc:

```bash
[akmoch@acer1 stargate-core]$ gradle clean dist
:clean
:compileJava
/home/akmoch/dev/build/stargate-core/src/main/java/com/tuplejump/stargate/Fields.java:124: error: method serialize in class CollectionType<T> cannot be applied to given types;
            return collectionType.serialize(collection);
                                 ^
  required: Name,List
  found: List<Pair<ByteBuffer,Column>>
  reason: actual and formal argument lists differ in length
  where T is a type-variable:
    T extends Object declared in class CollectionType
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.304 secs
```

When copying the resulting libs from successfully compiled stargate-core github master branch or the provided static download into a Cassandra 2.1.5 installation and following the **quickstart**, I get an error message in the moment of creating the custom index on the special field:

```bash
ServerError: <ErrorMessage code=0000 [Server error] message="java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.cassandra.config.CFMetaData.getCfDef()Lorg/apache/cassandra/cql3/CFDefinition;">
```

The NoSuchMethodException in fact also appears when trying to compile stargate-core against the **2.1.x** Cassandra version (on of many compile errors)

Nevertheless the idea behind stargate-core is relatively simple, by interfacing with Cassandra's RowIndex  with a Lucene implementation. Lucene is configured to use its own efficient file/dir index mechanism and obviously only indexes data that exists on the local Cassandra node. 

Disadvantage is keeping up with Cassandra developments and possibly 'interfering' with Cassandra's native stability by introducing some external libs.

I tweetet the TupleJump/stargate-core people if they have plans to advance to latest cassandra versions.

**Comment by allixender** [comment]
- KeyIndex Range check and io.cassandra.spatial.SpatialRasterRDDReader check!!! => it's right in space time
- check with Accumulo RastercatalogSpec.scala test every single tile

**Comment by allixender** [comment]
One challenge is actually to differentiate between Spark Cassandra Connector exposing tables as CassandraRRD in Spark, which is an abstraction, and the underlying table and indexing structure, which should be optimised for spatio-temporal filtering. Cassandra does support range queries, and `IN` selectors, but such capabilities largely depend on the indexing schemes, choice of what is the partition key, which are the secondary indices and number of fields used in composite/compound keys. And then how this can then be propagated through to RRD usage.

**Comment by lossyrob** [comment]
We've implemented and merged a Cassandra backend, closing.
