### ISSUE TITLE
Updating GeoTrellis Sphinx-built docs

### ISSUE THREAD

**Issue by allixender** [geotrellis/geotrellis#1100]
**GSoc2015 GeoTrellis Cassandra tracker for shared scratch documentation**

Fixing up some typos and TODOs.

**Comment by allixender** [comment]
`vagrant up` / `apt-get` didn't find the right nginx package

I followed the README, `git clone geotrellis-site`, `cd` into and `vagrant up` ...
```bash
TASK: [azavea.nginx | Configure the Nginx (Stable) PPA] *********************** 
changed: [default]

TASK: [azavea.nginx | Install Nginx] ****************************************** 
failed: [default] => {"failed": true}
stderr: E: Version '1.6.2-2+trusty0' for 'nginx' was not found

stdout: Reading package lists...
Building dependency tree...                                                                                                                                                 
Reading state information...                                                                                                                                                

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'nginx=1.6.2-2+trusty0'' failed: E: Version '1.6.2-2+trusty0' for 'nginx' was not found                                                                                                                                                   


FATAL: all hosts have already failed -- aborting                                                                                                                            

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/akmoch/site.retry

default                    : ok=7    changed=5    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I retried by updating to **1.6.3-1+trusty0** in `build/roles/azavea.nginx/defaults/main.yml` (2015 package, didn't work), finally got `1.8.0-1+trusty1` installed

http://www.ubuntuupdates.org/ppa/nginx?dist=trusty

**Comment by allixender** [comment]
Update:

After the nginx fix the vagrant vm would nicely build and serve the site and the docs.

For local dev, Sphinx for Python2.7 works, for Python3.4 doesn't work immediately:

```bash
[akmoch@acer1 geotrellis-site]$ sphinx-build docs/ /tmp/sphinxtarget
Running Sphinx v1.3.1
WARNING: extension 'sphinx.ext.mathbase' has no setup() function; is it really a Sphinx extension module?
WARNING: the config value 'html_add_permalinks' has type `NoneType', defaults to `str.'
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 42 source files that are out of date
updating environment: 42 added, 0 changed, 0 removed
reading sources... [  9%] documentation/geotrellis-geotools/index
Exception occurred:
  File "/usr/lib/python3.4/codecs.py", line 493, in read
    data = self.bytebuffer + newdata
TypeError: can't concat bytes to str
The full traceback has been saved in /tmp/sphinx-err-k4rqu75k.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

As I have Python2 and Python3 installed in parallel and Python3 is default and Python2 tools have a "2" attached, I could successfully `export SPHINX_PATH=/usr/bin/sphinx-build2` and run `./sbt "project site" run` on my local machine. 

A few glitches came up, but it didn't seem to have affected the build. It also seems that some typos have already been fixed in the repo, whereas the GeoTrellis online site still serves those :-)

```bash
[info] Running Sphinx v1.3.1
[info] loading pickled environment... not yet created
[error] WARNING: extension 'sphinx.ext.mathbase' has no setup() function; is it really a Sphinx extension module?
[error] WARNING: the config value 'html_add_permalinks' has type `NoneType', defaults to `unicode.'
```

and ...

```bash
[error] /home/akmoch/dev/build/geotrellis-site/docs/documentation/geotrellis/raster/index.rst:: WARNING: using "math" markup without a Sphinx math extension active, please use one of the math extensions described at http://sphinx-doc.org/ext/math.html
[error] /home/akmoch/dev/build/geotrellis-site/docs/documentation/geotrellis/raster/index.rst:: WARNING: using "math" markup without a Sphinx math extension active, please use one of the math extensions described at http://sphinx-doc.org/ext/math.html
[error] /home/akmoch/dev/build/geotrellis-site/docs/documentation/geotrellis/raster/index.rst:: WARNING: using "math" markup without a Sphinx math extension active, please use one of the math extensions described at http://sphinx-doc.org/ext/math.html
```

**Comment by lossyrob** [comment]
We need a way to version our documentation...how do we archive 0.9 documentation while developing 0.10 docs?

**Comment by lossyrob** [comment]
Also, to fix the nginx bug, fix up the roles.txt in the build folder to upgrade azavea-nginx to version 0.2.1

**Comment by allixender** [comment]
Also to check, how/which IDE to setup for geotrellis development (IDEA and maybe Eclipse), to actually see deps, class hierarchies, imports ...

For exercise sake could write that IDE setup experience in the 0.10.0-SNAPSHOT Sphinx doc

**Comment by allixender** [comment]
Restructuring the documentation folder and keeping the different versions in separate folders might be the most straightforward way of keeping the lines of documentation for the different geotrellis versions. Some argue, keeping docs separate from the source dirs, and dragging old docs along might be overhead, but it's really simple.

Labels and cross-references need to be versioned (as in the label should contain the version) then too though, as they ll live under the same sphinx build execution environment. This is due to the legacy, that the whole site is built under the same sphinx build, therefore factoring out documentation would be rather unnecessary effort.

![docsversions_s](https://cloud.githubusercontent.com/assets/4483885/7803332/4f186e2c-033c-11e5-8404-8796c055ec31.png)

**Comment by allixender** [comment]
A try with Eclipse and IDEA with geotrellis and sbt plugins, to set up IDE friendly project configuration:
```scala
// addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "3.0.0")

// addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.6.0")
```
Eclipse unfortunately would not pick up all "inter-project" dependencies, like in geotrellis-spark it wouldn't pull in geotrellis-raster and geotrellis-proj4.

I tried fiddling around with the Build.scala etc without luck.

With IDEA it looked somewhat more promising, but I am a novice with IDEA and Scala setup. Apparently IntelliJ IDEA scala plugin has support to import native sbt projects. It would recognise that the `sbt-idea` plugin had generated the project description and advised to import native.

I guess we could add those "IDE considerations" (including the [link from Chuck](https://groups.google.com/forum/#!topic/geotrellis-user/4R_QSEUZZ9A) ) somewhere to the docs?

**Comment by allixender** [comment]
**Update Eclipse IDE and GeoTrellis**

With additional linked source folders configured on the build build path in Eclipse it is possible to add the missing dependencies. So sbteclipse-plugin was added to `project/plugins.sbt` and then just execute `./sbt eclipse`

This results in a eclipse project configuration for **each** geotrellis subproject/module, It'll also try to be all Scala 2.11 and show some errors that Scala versions are also of 2.10, this doesn't affect the programming or type resolution, only causes red lines and exclamation marks in the IDE representation.

![eclipse1](https://cloud.githubusercontent.com/assets/4483885/7805408/583b9090-0361-11e5-8d6a-1d95ad1d3d6c.png)

In Eclipse right click on the project in the left outline, choose `configure build path`. Just adding the related projects won't work (add them like this, but it's not enough :smiley_cat: )

![eclipse2-buildpath1](https://cloud.githubusercontent.com/assets/4483885/7805433/c4796408-0361-11e5-9d56-cc6d7024146d.png)

For manageability I added linked folders via variables (e.g. GT_VECTOR: $WORKSPACE/geotrellis-vector), and then used the  variables to actually link in the $GT_VECTOR/src/main/scala folder into the geotrellis-spark project. Then those depemdencies would resolv. Eclipse also sees some implicit context items e.g. implicit conversions.

**Comment by allixender** [comment]
IDE setup draft write up at [http://allixender.github.io/articles/gsoc-geotrellis-ides/](http://allixender.github.io/articles/gsoc-geotrellis-ides/).

**Comment by allixender** [comment]
we might as well close this issue now? all info has been compiled either in the blog post or in the geotrellis-site pull requests?

**Comment by lossyrob** [comment]
@allixender one good way to make sure that PR's that fix issues close the issue is, in the PR description, say "Fixes #XXX" or "Closes #XXX", where XXX is the issue number. Github automagically picks up on that language and closes the issue when the PR is merged.
