### ISSUE TITLE
HdfsUtils tif vs tiff extension and recursive input glob pattern

### ISSUE THREAD

**Issue by allixender** [geotrellis/geotrellis#1116]
- particularly important for geotiff ingest jobs
- tif vs/and .tiff extension, input glob pattern should match the files, or at least it should be clear if only on form is working
- apparently tiff is the more popular (correct?) extension
- recursive is wanted, but in fact right now does it really? To be verified!

**Comment by echeipesh** [comment]
Connects: https://github.com/geotrellis/geotrellis/pull/1151
