### ISSUE TITLE
GeoTiff Reader unable to parse CRS set by gdal_edit.py

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis#1125]
When ingesting some GeoTiffs that did not have a CRS set I set it using `gdal_edit`:
`gdal_edit.py -a_srs "EPSG:3857" something.tif`

This produces following :
```
Coordinate System is:
PROJCS["WGS 84 / Pseudo-Mercator",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["central_meridian",0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"],
    AUTHORITY["EPSG","3857"]]
```

`TiffTagsReader` is attempting to read the proj4 string to determine CRS and fails out with `None`, which gets upgraded to `LatLng`.

As a work around I'm able to set CRS as proj4 string:
`gdal_edit.py -a_srs "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs" something.tif`

**Comment by lossyrob** [comment]
This should be fixed with the changes to the CRS reading in the GeoTiff. @notthatbreezy @echeipesh can you confirm?

**Comment by lossyrob** [comment]
Confirmed
