### ISSUE TITLE
Upgrade OpenCSV

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1128]
Currently the proj4 project uses openCVS, but a 2.3 version not from `com.opencsv`. We should move to this:

http://search.maven.org/#artifactdetails%7Ccom.opencsv%7Copencsv%7C3.4%7Cbundle

**Comment by adamkozuch** [comment]
Should this be the newest version 3.4 or keep 2.3?

**Comment by lossyrob** [comment]
It would be best to move to the latests, so unless there's a good reason not to 3.4 sounds like the right choice. Thanks @adamkozuch

**Comment by adamkozuch** [comment]
It can be closed.
