### ISSUE TITLE
Dependency issues: GDAL and ScalaZ stream

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1135]
We depend on the following in geotrellis-spark 0.10.0-M1.

This causes errors when trying to use the library without some repos in the `resolvers`. We should require our users to have unfound dependencies and have to debug to figure out how to include these transitive dependencies.

```scala
  "org.scalaz.stream" %% "scalaz-stream" % "0.7a"
  "org.gdal"         % "gdal"       % "1.10.1"
```

The solution to the GDAL one is, don't have geotrellis-spark depend on the gdal project (it shouldn't anyway). geotrellis-gdal clearly needs it, but there should be documentation about needing to add the opengeo repository.

@echeipesh, what about scalaz-stream? Is this library not on maven central? In order to use it, will we require users to have to put in the "Scalaz Bintray Repo" at "https://dl.bintray.com/scalaz/releases" resolver? That would not be ideal. Also, what does the 'a' in the version string mean? Is this a stable release?

Moving forward, we should be wary of adding any dependency that is not a released version and is not on maven central.

**Comment by pomadchin** [comment]
There is only an old version of scalaz on mvn central, there is an issue: https://github.com/scalaz/scalaz-stream/issues/258

**Comment by lossyrob** [comment]
@pomadchin thanks for pointing that out. It's been open for months, with a lot of people clamoring for it to happen, and still it's not up? Strange. Add us to the list I guess. Hopefully this gets resolved before we want to put out a proper 0.10.0 release.

**Comment by echeipesh** [comment]
We depend on GDAL for `sc.gdalRDD` and `sc.netCdfRDD` in the spark project.

As for "0.7a" version, it's their way of tracking both scalaz-7.1 and scalaz-7.0 as a dependency. There are some "incompatibilities" the apparently require this. https://gist.github.com/djspiewak/d93a9c4983f63721c41c.

**Comment by hectcastro** [comment]
Only sightly related, but I recently fixed an issue with GDAL dependency resolution by adding the OpenGeo repository, but with the following endpoint:

```scala
resolvers += "OpenGeo" at "https://boundless.artifactoryonline.com/boundless/main"
```

See also: https://github.com/WikiWatershed/mmw-geoprocessing/pull/12

**Comment by echeipesh** [comment]
scalaz-streams is now on maven central, thanks to Bintray, resolved with https://github.com/geotrellis/geotrellis/pull/1188

Feels like GDAL should still be broken out into subproject since it imposes restrictions on our environment.

**Comment by lossyrob** [comment]
Note: geotrellis-gdal functionality now lives in https://github.com/geotrellis/geotrellis-gdal
