### ISSUE TITLE
Use of Kryo for persistence

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis#1138]
Just spent a good chunk of time debugging a problem that can be summarized as:

Kryo serializer/de-serializer does not behave as expected when running program through `spark-submit` vs through `sbt run`. To clarify: in order to use `sbt run` `provided` tag must be removed from `spark-core` in dependencies list.

The error can have two forms: 
**If classes being serialized with kryo are registered** 

While deserializing `(LayerId, KeyIndex[K])` in AttributeStore.
Serialization from `spark-submit` kryo will be one lower than then serialization from `sbt run` kryo in the   first byte. (ex: `Array[Byte](51, 1)` vs `Array[Byte](52, 1))`. The first byte represents and ID kryo has assigned to the class when it is registered and the offset by one is preserved if the order of registration is changed.

**If classes being serialized are not registered**

Unregistered classes forces Kyro to use full class names when serializing and the  `(LayerId, KeyIndex[K])` tuple is deserialized without issue. (the serialized bytes match up exactly).

However when reading `(K, Tile)` through the tile reader several things are possible:
"Unregistered class ID 0000 encountered" when some other common types are registered with Kryo.
or "scala.Tuple1 cannot be cast to scala.Tuple2" when no additional classes are registered with Kryo.

In both cases running the program through `spark-submit` allows it to correctly deserialize both the metadata and the tile tuples.

**Why**
We pressgang the spark `KryoSerializer` into our service here. A good guess is that it somehow goes through different initialization between the two scenarios.

**Comment by joshmarcus** [comment]
It sounds like this comment may be too late to be helpful, but did you know that you can give classes explicit integer keys when you register them with Kryo?

**Comment by echeipesh** [comment]
Yes, I looked at that. Since we're borrowing sparks kryo serializer, not sure if you are, the base registered class starts at 31, it could go up with the next version of spark and offset the whole registration section. Then there is the strange behavior where two instance of spark one started with spark-submit and the other with it's own context will not agree on serialization format.

Overall Avro, or something like it, provides well defined binary format that is not tied to the class implementation. It's nowhere near as easy to use as Kryo, but I guess you can't have your cake and eat it too.

**Comment by echeipesh** [comment]
Resolved with use of Avro for catalogs
