### ISSUE TITLE
Put `.envelope` on Geometry

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1148]
@jwalgran had to do this, which looks a bit silly: https://github.com/azavea/datahub-services/blob/28f5ac6472c210527af1b2f1a37766a538050075/summary/src/main/scala/SummaryJob.scala#L87

But is required because we don't have `.envelope` on Geometry. We should...and it shouldn't have to be overloaded by anything.

Currently the implementations are `lazy val`s. I'd like to get away from that and make them `defs`, so

```scala
lazy val envelope: Extent =
    jtsGeom.getEnvelopeInternal

// becomes

def envelope: Extent = 
  jtsGeom.getEnvelopeInternal

// in geotrellis.vector.Geometry
```

@allixender can you take a look at this?

**Comment by allixender** [comment]
@lossyrob , I can't open the link, github says page not found.

However, I had a look and this is only declared in a few of the Geometriy types, any reason? But yes, I'll look into it. Wouldn't it makes sense that you could called virtually on any Geometry (or even maybe  Feature) types?

**Comment by lossyrob** [comment]
Features are implicitly convertible to geometry types, so no need to put on features. But yes should be called on any Geometry type.

**Comment by allixender** [comment]
Right: features.getAllPolygons.envelope
