### ISSUE TITLE
Get rid of broadcast variables in our RasterRDDReaders

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1154]
There's some `sc.broadcast`s we are doing as a workaround to `TaskNoSerializable` exceptions. Instead of working around that, we need to figure out how to only be passing serializable things.

**Comment by zifeo** [comment]
Decorating the broadcasted content by `KryoWrapper` seems to be work also as @echeipesh suggested on Gitter.
```scala
val writeCodec = sc.broadcast(TupleCodec[SpatialKey, Tile]) // ante
val writeCodec = KryoWrapper(TupleCodec[SpatialKey, Tile]) // post
```

**Comment by echeipesh** [comment]
This has happened through out multiple PRs. The current approach is to let spark send out whatever is possible through normal closure semantics and using `KryoWrapper` for objects from external libraries that are not `Serializable` (ex: `Schema` from Avro library)
