### ISSUE TITLE
Partition control on HDFS ingest.

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis#1157]
It is possible to control the size of each partition of the source RDD during ingest/ETL on S3 by setting `splitSize` argument: https://github.com/geotrellis/geotrellis/blob/master/spark-etl/src/main/scala/geotrellis/spark/etl/s3/S3Input.scala#L17

There is no such control exists for HDFS ingest where `FileInputFormat` will produce a partition per file. Since files often are quite small, this is a potential source of inefficiency. A way to call `RDD.coalesce` before returning source RDD may be sufficient as its guaranteed to be fast. Although ,in general, asking for number of partitions is not as useful as limiting the same of each partition and letting the number of partitions float.

**Comment by lossyrob** [comment]
This could be done with a `coalesce` on the client side. If the user is using `spark-etl`, then that would require us allowing them to manipulate the incoming source RDD, which is no yet available.

**Comment by lossyrob** [comment]
We can now manipulation the source tiles in ETL, closing.
