### ISSUE TITLE
Metadata treatment in *LayerReader, *LayerWriter

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis#1193]
When writing the LayerReader and LayerWriter classes I made a decision to treat metadata type existentially, in order to keep it out of already long parameter list of those classes. Currently it is a path dependent type that is brought in through `ContainerConstructor`:
https://github.com/geotrellis/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/ContainerConstructor.scala#L20

However, this pretty much results in any manipulation on that type having to be done through `ContainerConstructor` instance, as it creates a new, path dependent, type for the Metadata. 

Current symptoms are:
- Having to carry `JsonFormat[MetaDataType]` in constructor instance
- RDDFilter casts:
https://github.com/geotrellis/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/RDDFilter.scala#L72 (this requires `reflectiveCalls`)
- `ContainerConstructor.combineMetaData` method in #1192 

The only way out seems to be to give up and include `MetaDataType` as a type parameter here:
https://github.com/geotrellis/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/s3/S3LayerReader.scala#L27

I think the length of that parameter list would almost require to create subclasses for common cases:

```
class SpatialS3LayerReader extends S3LayerReader[SpatialKey, Tile, RasterMetaData, RasterRDD[SpatialKey]]
// or
class TileS3LayerReader[K] extends S3LayerReader[K, Tile, RasterMetaData, RasterRDD[K]]
// ... since MetaDataType is tied to value type.
```

It should be noted that having more concrete subclasses would reduce the number of required implicit in scope for initialization. For instance avro codecs would already be closed over in both of those cases.

In general there is a desire to "stop messing" with readers/writers. So the most sustainable/expansible is desirable.

**Comment by lossyrob** [comment]
In your opinion, would including it in the parameter list be the more sustainable/expansible solution?

**Comment by echeipesh** [comment]
I think so as well. This pattern of putting more things into `ContainerConstructor` concerning. Can you think of any downsides of expanding the argument list and subclassing?

**Comment by lossyrob** [comment]
> I think so as well

I didn't state an opinion there ;) but I catch your drift. The only downside is ugliness as far as I can tell, but I think if it's necessary then it's necessary.

**Comment by lossyrob** [comment]
This issue has changed to adding object apply methods to Layer Reader/Writers, and at this point we still need to create apply methods for spaceTimeKey/spaceTimeMultiBand, and for writers
