### ISSUE TITLE
Geotiff reader fails when using modeltransformation

### ISSUE THREAD

**Issue by jdries** [geotrellis/geotrellis#1200]
A Geotiff can specify its georeferencing by using a transformation matrix (in my case, it was written by geotools). The geotrellis reader failed to read due to two issues when determining the model bounds based on this transformation. 
* When multiplying the matrix with a vector, in TiffTags.transformationModelSpace, replaced Array(Array(pixel.x, pixel.y, pixel.z, 1)) with Array(Array(pixel.x),Array( pixel.y),Array( pixel.z),Array( 1)))
* In the matrix multiplication itself (MatrixExtensions.scala) replaced sum += matrix(i)(j) * second(k)(j) with sum += matrix(i)(k) * second(k)(j)

I can provide a file that triggers this issue if necessary.

**Comment by jdries** [comment]
This is the tiff metadata:
TIFF Directory at offset 0x8 (8)
  Image Width: 1121 Image Length: 1121
  Resolution: 1, 1 (unitless)
  Bits/Sample: 8
  Compression Scheme: AdobeDeflate
  Photometric Interpretation: min-is-black
  Samples/Pixel: 1
  Rows/Strip: 8
  Planar Configuration: single image plane
  Tag 34264: 0.008921,0.000000,0.000000,59.995540,0.000000,-0.008921,0.000000,40.004460,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
  Tag 34735: 1,1,2,3,1024,0,1,2,1025,0,1,1,2048,0,1,4326
  Tag 42113: 0.0

Bounds according to GDAL:
Corner Coordinates:
Upper Left  (  59.9955397,  40.0044603) ( 59d59'43.94"E, 40d 0'16.06"N)
Lower Left  (  59.9955397,  30.0044603) ( 59d59'43.94"E, 30d 0'16.06"N)
Upper Right (  69.9955397,  40.0044603) ( 69d59'43.94"E, 40d 0'16.06"N)
Lower Right (  69.9955397,  30.0044603) ( 69d59'43.94"E, 30d 0'16.06"N)
Center      (  64.9955397,  35.0044603) ( 64d59'43.94"E, 35d 0'16.06"N)
Band 1 Block=1121x8 Type=Byte, ColorInterp=Gray

**Comment by lossyrob** [comment]
Thanks for the detailed report. Could you share the offending GeoTIFF? If it's small enough you could do it with a commit to a branch, so I could pull it down and make sure we can handle this case.

**Comment by jdries** [comment]
Not sure if this works, but I've attached it to this mail, it's only 600kb.



Jeroen Dries
TAP - Centre for Remote Sensing and Earth Observation Processes
VITO NV | Boeretang 200 | 2400 Mol
tel. +32 14 33 55 11 | jeroen.dries@vito.be<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=mailto%3avoornaam.naam%40vito.be>
[cid:image001.jpg@01CDCE3A.4E197A50]<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=http%3a%2f%2fwww.vito.be%2f>[cid:image001.jpg@01CD3F0D.B57AA190]<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=http%3a%2f%2fwww.linkedin.com%2fcompany%2f17947>[cid:image003.jpg@01CD3F0D.B57AA190]<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=http%3a%2f%2ftwitter.com%2f%23%21%2fvitobelgium>[cid:image002.jpg@01CD3F0D.B57AA190]<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=https%3a%2f%2fwww.facebook.com%2fVITObelgium>
________________________________
Van: Rob Emanuele <notifications@github.com>
Verzonden: woensdag 11 november 2015 00:27
Aan: geotrellis/geotrellis
CC: Dries Jeroen
Onderwerp: Re: [geotrellis] Geotiff reader fails when using modeltransformation (#1200)


Thanks for the detailed report. Could you share the offending GeoTIFF? If it's small enough you could do it with a commit to a branch, so I could pull it down and make sure we can handle this case.

-
Reply to this email directly or view it on GitHub<https://github.com/geotrellis/geotrellis/issues/1200#issuecomment-155600806>.

VITO Disclaimer: http://www.vito.be/e-maildisclaimer
