### ISSUE TITLE
Document the geotrellis.slick package

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1219]
There needs to be docs for the geotrellis-slick package. Explaining what is needed to run the unit tests should be included.

**Comment by adamkozuch** [comment]
Should this be just good readme or also scaladocs ?

**Comment by lossyrob** [comment]
The more docs the better...a good readme with examples is what this issue is about, but also some pending work is to go through the packages and make sure scaladocs are useful as well.

**Comment by adamkozuch** [comment]
OK. I have very early  sketch https://gist.github.com/adamkozuch/2d5d8729fa96b56e4b3e and I have some questions related to issue.
1. Should I describe step by step process of creating Table in Slick or just make a reference to Slick docs? Should I assume that reader don't know Slick at all?
2. Should I include things like database configuration?
3. Should I include a description of supported geometries?
4. Not sure if I should define things like SRID or just make reference to Wikipedia etc. ?

**Comment by moradology** [comment]
There's some Slick documentation in a PR that's probably worth looking at in this context: https://github.com/geotrellis/geotrellis/pull/1365/files

**Comment by adamkozuch** [comment]
I didn't notice it. Thanks.

**Comment by lossyrob** [comment]
@adamkozuch can you work off of @moradology's branch to merge the docs? That would be really helpful as your docs contain good info.

Also, are you currently using the slick package? I haven't used it in a while, and just want the data point that it's working out well for someone.

**Comment by adamkozuch** [comment]
If you mean geotrellis-slick then I just started to learn it but I have experience with Slick 3.0. Now I wonder if there is a reason to keep 2.1 version? Maybe it would be better to update it to 3.0 or 3.1 and then write some docs or tutorial for it?

**Comment by lossyrob** [comment]
@adamkozuch the only reason we haven't upgraded is because we haven't had someone with capacity to test the upgrade. If you're willing to do that that would be a huge help.

**Comment by lossyrob** [comment]
Further work on this will be done on #1383, so this issue should be closed with #1365
