### ISSUE TITLE
Layer management functions

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis#1225]
There can be following management functions: 
 * `delete` (it's all clear with it)
 * `reindex` 
 * `rename` 
 * `copy`
 * `move`

The question is in a difference between `rename`, `copy` and `move` functions. How `rename` differs from `move`, and `move` from `copy`? (For example in `Accumulo`, to move layer, means to copy it, and rewrite with another `LayerId`).

Just wrote a quick sample of a `LayerMover`, it seems we have to pass `LayerReader`, `LayerWriter` and `LayerDeleter` into `mover | copier`: https://gist.github.com/pomadchin/31773571222b4098aa8b is not it a problem? (It seems to me that this object becomes too fat)

Current layer management super types:

1: 
```scala
trait LayerCopier[ID] {
  type Header

  def headerUpdate(id: ID, header: Header): Header

  def copy(from: ID, to: ID): Unit
}

trait LayerMover[ID] {
  val attributeStore: AttributeStore[JsonFormat]
  val layerCopier: LayerCopier[ID]
  val layerDeleter: LayerDeleter[ID]

  def move(from: ID, to: ID): Unit = {
    layerCopier.copy(from, to)
    layerDeleter.delete(from)
  }
}

trait LayerReindexer[ID] {
  val layerDeleter : LayerDeleter[ID]
  val layerMover   : LayerMover[ID]
  val layerCopier  : LayerCopier[ID]

  def getTmpId(id: ID): ID

  def reindex(id: ID): Unit = {
    val tmpId = getTmpId(id)
    layerCopier.copy(id, tmpId)
    layerDeleter.delete(id)
    layerMover.move(tmpId, id)
  }
}
```

2: 
```scala
trait LayerCopier[ID] {
  def copy(from: ID, to: ID): Unit
}

abstract class SparkLayerCopier[Header: JsonFormat, K: Boundable: JsonFormat: ClassTag, V: ClassTag, Container](
   val attributeStore: AttributeStore[JsonFormat],
   layerReader: FilteringLayerReader[LayerId, K, Container],
   layerWriter: Writer[LayerId, Container with RDD[(K, V)]])
  (implicit val cons: ContainerConstructor[K, V, Container], containerEv: Container => Container with RDD[(K, V)]) extends LayerCopier[LayerId] {
...
}

trait LayerMover[ID] {
  def move(from: ID, to: ID): Unit
}

class GenericLayerMover[ID](layerCopier: LayerCopier[ID], layerDeleter: LayerDeleter[ID]) extends LayerMover[ID] {
  def move(from: ID, to: ID): Unit = {
    layerCopier.copy(from, to)
    layerDeleter.delete(from)
  }
}

trait LayerReindexer[ID] {
  val layerDeleter : LayerDeleter[ID]
  val layerMover   : LayerMover[ID]
  val layerCopier  : LayerCopier[ID]

  def getTmpId(id: ID): ID

  def reindex(id: ID): Unit = {
    val tmpId = getTmpId(id)
    layerCopier.copy(id, tmpId)
    layerDeleter.delete(id)
    layerMover.move(tmpId, id)
  }
}
```

3: 
```scala
trait LayerCopier[ID] {
  def copy(from: ID, to: ID): Unit
}

abstract class SparkLayerCopier[Header: JsonFormat, K: Boundable: JsonFormat: ClassTag, V: ClassTag, Container](
   val attributeStore: AttributeStore[JsonFormat],
   layerReader: FilteringLayerReader[LayerId, K, Container],
   layerWriter: Writer[LayerId, Container with RDD[(K, V)]])
  (implicit val cons: ContainerConstructor[K, V, Container], containerEv: Container => Container with RDD[(K, V)]) extends LayerCopier[LayerId] {
...
}

trait LayerMover[ID] {
  def move(from: ID, to: ID): Unit
}

class GenericLayerMover[ID](layerCopier: LayerCopier[ID], layerDeleter: LayerDeleter[ID]) extends LayerMover[ID] {
  def move(from: ID, to: ID): Unit = {
    layerCopier.copy(from, to)
    layerDeleter.delete(from)
  }
}

trait LayerReindexer[ID] {
  def reindex(id: ID): Unit
}

abstract class GenericLayerReindexer[ID](
  layerDeleter: LayerDeleter[ID],
  layerMover  : LayerMover[ID],
  layerCopier : LayerCopier[ID]) extends LayerReindexer[ID] {

  def getTmpId(id: ID): ID

  def reindex(id: ID): Unit = {
    val tmpId = getTmpId(id)
    layerCopier.copy(id, tmpId)
    layerDeleter.delete(id)
    layerMover.move(tmpId, id)
  }
}
```

**Comment by pomadchin** [comment]
Providing an additional information:

|        | S3  | Accumulo | Hadoop |
|--------|-----|----------|--------|
| move   | no | no       | yes    |
| rename | no | no       | yes    |
| copy   | yes | yes      | yes    |

* With `copy` it's all clear, to grab any layer by its `LayerId` and save as some other `LayerId`.
* With both `Accumulo` and `S3` it is not possible to rename Layers (we have to rename files in `S3` case and to change column family in `Accumulo` case and these things are not possible without copying).
* It is possible to move and rename files on `HDFS`

Although, should be there provided such functions changing `table` / `path`? May be it is also reasonable to add such functions to `LayerDeleter`, to make possible to delete `table` / `path`?

**Comment by pomadchin** [comment]
Implemented some samples of `LayerMover`. In fact, move function can be only provided for `Hadoop` (`rename`), for other backends it's just a composition of `LayerCopier` and `LayerDeleter`.

**Comment by echeipesh** [comment]
My opinion is that the generic move method on `LayerManager` can rely on an instance of `LayerMover` and `LayerDeleter`. Then the concrete `HadoopLayerManager` can override the method to instantiate and use the special `HadoopLayerMover`. 

I'm not sure how much utility for the user there is in capturing a combination of `Copy/Delete` in an interface.

**Comment by pomadchin** [comment]
`LayerCopier` has specific implementations for `S3` and `Hadoop`. For `Accumulo` it has `Spark` implementation, which in fact is generic, and can be used by any `Geotrellis` backend.

abstract class SparkLayerCopier[LayerHeader: JsonFormat, K: Boundable: JsonFormat: ClassTag, V: ClassTag, Container](
   val attributeStore: AttributeStore[JsonFormat],
   layerReader: FilteringLayerReader[LayerId, K, Container],
   layerWriter: Writer[LayerId, Container with RDD[(K, V)]])
  (implicit val cons: ContainerConstructor[K, V, Container], containerEv: Container => Container with RDD[(K, V)]) extends LayerCopier[LayerId] {

  type Header = LayerHeader

  def copy(from: LayerId, to: LayerId): Unit = {
    if (!attributeStore.layerExists(from)) throw new LayerNotFoundError(from)
    if (attributeStore.layerExists(to)) throw new LayerExistsError(to)
    implicit val mdFormat = cons.metaDataFormat
    val (existingLayerHeader, existingMetaData, existingKeyBounds, existingKeyIndex, existingSchema) = try {
      attributeStore.readLayerAttributes[Header, cons.MetaDataType, KeyBounds[K], KeyIndex[K], Schema](from)
    } catch {
      case e: AttributeNotFoundError => throw new LayerCopyError(from, to).initCause(e)
    }

    try {
      layerWriter.write(to, layerReader.read(from))
      attributeStore.writeLayerAttributes(
        to, headerUpdate(to, existingLayerHeader), existingMetaData, existingKeyBounds, existingKeyIndex, existingSchema
      )
    } catch {
      case e: Exception => new LayerCopyError(from, to).initCause(e)
    }
  }
}

**Comment by pomadchin** [comment]
For `Accumulo` copier is possible to use https://accumulo.apache.org/1.6/apidocs/org/apache/accumulo/core/iterators/user/TransformingIterator.html (it makes possible to change column family), but not sure this can help to reindex data.

**Comment by lossyrob** [comment]
For

```scala
trait LayerMover[ID] {
  val attributeStore: AttributeStore[JsonFormat]
  val layerCopier: LayerCopier[ID]
  val layerDeleter: LayerDeleter[ID]

  def move(from: ID, to: ID): Unit = {
    layerCopier.copy(from, to)
    layerDeleter.delete(from)
  }
}
```

I think the trait should not require the layerCopier and layerDeleter. That should be a generic implementation detail

```scala
trait LayerMover[ID] {
  def move(from: ID, to: ID): Unit 
}

class GenericLayerMover[ID](
  layerCopier: LayerCopier[ID],
  layerDeleter: LayerDeleter[ID]
) {
  def move(from: ID, to: ID): Unit = {
    layerCopier.copy(from, to)
    layerDeleter.delete(from)
  }
}

class SomethingElseLayerMover[ID](
  attributeStore: AttributeStore[JsonFormat]
) {
  // This one might only need the attribute store
  def move(from: ID, to: ID): Unit = {
    ???
  }
}
```

**Comment by pomadchin** [comment]
Cool, fixed up to @lossyrob suggestion.

**Comment by lossyrob** [comment]
@pomadchin so the `Reindexer` should have a similar change, yeah? Because it's possible to implement reindex without the mover/deleter. Or is that not true.

```scala
trait LayerReindexer[ID] {
  def reindex(id: ID): Unit =
}

abstract class GenericLayerReindexer[ID](
  val layerDeleter : LayerDeleter[ID],
  val layerMover   : LayerMover[ID],
  val layerCopier  : LayerCopier[ID]
) {

  def getTmpId(id: ID): ID

  def reindex(id: ID): Unit = {
    val tmpId = getTmpId(id)
    layerCopier.copy(id, tmpId)
    layerDeleter.delete(id)
    layerMover.move(tmpId, id)
  }
}
```

**Comment by pomadchin** [comment]
@lossyrob sure, not touched it yet, will make upd in a couple of minutes

**Comment by pomadchin** [comment]
updated (with reindexer)

**Comment by pomadchin** [comment]
Tried to implement `LayerManager` interface (to look how it's going to be in result) suggested by @lossyrob , so the result https://github.com/pomadchin/geotrellis/tree/feature/layer-manager

We can see that there appeared some functions inconsistent (due to the fact, that for all the backends is not enough to have only `attributeStore`)

* https://github.com/pomadchin/geotrellis/blob/feature/layer-manager/spark/src/main/scala/geotrellis/spark/io/accumulo/AccumuloLayerManager.scala
* https://github.com/pomadchin/geotrellis/blob/feature/layer-manager/spark/src/main/scala/geotrellis/spark/io/hadoop/HadoopLayerManager.scala
* https://github.com/pomadchin/geotrellis/blob/feature/layer-manager/spark/src/main/scala/geotrellis/spark/io/s3/S3LayerManager.scala

**Comment by lossyrob** [comment]
Closed via various PRs
