### ISSUE TITLE
Reproject should take border tiles into account

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1261]
During ingest, a step we normally do is to reproject the source tiles into the projection we want, and then continue on with the tiling/indexing stages.

The problem with this is, when we reproject individual tiles, we introduce errors at the tile borders. This can result in NoData artifacts in eventual mosiacs.

What we need to do is to utilize the `FocalOperation` method of including border tiles along with the tile of interest, and reproject a center window against a larger raster. If we do a windowed reproject with additional border tile information, there will not be the artificial NoData artifacts around the borders like I described.

This will require the Reproject logic to be changed to support windowed reprojects, a refactor of the `FocalOperation` architecture to allow it's border-tile-passing algorithm to be used outside of focal operations, an implementation of reprojection on spatially indexed `RDD[(K, TileType)]`'s, and a modification to the ingest processes for Ingest, `spark-etl`, and wherever it is used to do the reprojection after the initial tiling/indexing in the raster layer's native CRS.

**Comment by echeipesh** [comment]
To update this issue: The reproject logic now uses buffered tiles, similar to focal operations with: https://github.com/geotrellis/geotrellis/pull/1268

The remaining work is in changing ETL to perform buffered reproject:
- Read the input tiles
- Tile them in native CRS
- Perform buffered reproject to target layout.

**Comment by lossyrob** [comment]
Closed by https://github.com/geotrellis/geotrellis/pull/1268
