### ISSUE TITLE
API renames

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1267]
Prior to the 0.10 release, we want to make some renames to core types so that they are properly named before the release. This will break the API and any any client code pretty heavily, so this should be a one-shot thing.

```console
MultiBand -> Multiband
MetaData -> Metadata
SpatialKey -> GridKey
SpatialComponent -> GridComponent
SpaceTimeKey -> TimeGridKey
RasterRDD[K] -> TileRDD[K]
MultiBandRasterRDD[K] -> MultiBandTileRDD[K]
```

Moving `op` to `mapalgebra`, and moving any operations that are not map algebra to a different subpackage in the root package (e.g. `geotrellis.raster.op.local.LocalMethods.mask(ext: Extent, geoms: Traversable[Geometry], includeExterior: Boolean)` should be functionality in some `geotrellis.raster.mask` package)

**Comment by lossyrob** [comment]
@echeipesh @moradology @pomadchin @jamesmcclain @dwins can you think of others? Any feedback on these?

**Comment by pomadchin** [comment]
Nice catch with key types naming

**Comment by echeipesh** [comment]
+1 on class renames.

Less certain on the `op` -> `mapalgebra` move. What is the motivation, flatten the namespace a little? Are things in raster package going to mirror this move?

**Comment by lossyrob** [comment]
Fixed by https://github.com/lossyrob/geotrellis/pull/12
