### ISSUE TITLE
Windowed GeoTIFF reading

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1277]
Currently our GeoTiff reader reads all of the bytes of the GeoTiff file into memory. We have a method of only uncompressing the parts of the raster that we are working on with `GeoTiffTile`, but we do not yet have a way to read only the bytes from the file that we would need to satisfy a windowed read requests.

This would require the following basic steps:
- Read the GeoTiff tag data in as a stream, stop reading once there are no more tags left.
- Use the information contained in the tags to locate where data is in the file
- Create logic to read byte ranges out of the file based on query data such as the window extent.

**Comment by jamesmcclain** [comment]
I [wrote some C code](https://github.com/azavea/azavea-data-hub/tree/master/util/bigtiff_translation) to do something similar a while back.

**Comment by fosskers** [comment]
@lossyrob This is complete.
