### ISSUE TITLE
Byte Range reads via HTTP in GeoTiff reader (i.e. /vsicurl/ in GeoTrellis)

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1278]
Using `/vsicurl/`, GDAL can read remote HTTP rasters using the [Range HTTP request header](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35). This allows it to only read remote data that it needs to satisfy a request, for instance, a windowed read request. We should implement this by utilizing a 3rd party library for doing byte range reads of HTTP binary data, or, if no acceptable solution already exists, writing the networking logic that would allow this. This in combination with #1277 will allow us to work on very large remote GeoTiff data without having to download the whole image for each windowed read.

Depends on #1277

**Comment by jamesmcclain** [comment]
I [wrote some C code](https://github.com/azavea/azavea-data-hub/tree/master/util/bigtiff_translation) to do something similar a while back.
