### ISSUE TITLE
Covariance with type classes return types (Stitcher, Reproject, Merge)

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis#1292]
# The Setup

Type classes are great, they allow us minimize interdependency between code modules.
However, there is a common problem with variance. For instance we stitch a set of tiles together based on their (col, row) position in some tile layout:

```scala
trait Stitcher[T <: CellGrid] extends Serializable {
  def stitch(pieces: Iterable[(T, (Int, Int))]): T
}
```

We have two implementations which work on abstract classes `Tile` and `MultiBandTile`:

```scala
  implicit object TileStitcher extends Stitcher[Tile] {
    def stitch(pieces: Iterable[(Tile, (Int, Int))]): Tile = ???
  }

  implicit object MultiBandTileStitcher extends Stitcher[MultiBandTile] {
    def stitch(pieces: Iterable[(MultiBandTile, (Int, Int))]): MultiBandTile =  ???
  }
```

Now we can use it to generically stitch tiles:

```scala
def needStitching[T <: CellGrid : Stitcher](tiles: Seq[T]): T = {
  val pieces  = ??? // Transform tiles somehow
  implicitly[Stitcher[T]].stitch(pieces)
}
```

Except we run into problem we try to work with subtypes for either `Tile` or `MultiBandTile`:

```scala
val pieces: Seq[(IntArrayTile, (Int, Int))] = ???
needStitching(pieces)
//scala> could not find implicit value for parameter ev0: geotrellis.raster.stitch.Stitcher[geotrellis.raster.IntArrayTile]
```

# Contra Variance ... clearly?
That's right, `Stitcher[T]` is a box that does not vary with it's type parameter. We need it to vary ... in some manner.

Which direction to vary is always confusing to me so lets write on the margins and make sense of mechanics.
The answer we're questioning is: When performing assignment, what types are acceptable on the right hand side?

```scala
  class Base
  class Sub extends Base

  trait Box[T]                    // Box is invariant
  val b: Box[Sub] = new Box[Sub]  // Only one, exact type of parameter is acceptable, boo
```

```scala
  trait Box[+T]                   // Box is covariant with T ("normal" case)
  val b: Box[Base] = new Box[Sub] // Any Box that has a subclass of Base will do
```
This is normal Liskov substitution rules. Anything that is defined on a subtype of `Base`, `S`, must work when given `Base` because any definition of `S` must have the same interface as `Base`. Makes sense.

```scala
  trait Box[-T]                   // Box is contra variant with T
  val b: Box[Sub] = new Box[Base] // Just the reverse, we can go up the type tree instead of down.
```

Back to our use case. What we're really trying to say is that when implicitly looking for a `Stitcher[IntArrayTile]` we would be more than happy with instance of `Stitcher[Tile]`:
Or during implicit assignment: `val stitcher: Stitcher[IntArrayTile] = new Stitcher[Tile]` should be ok.
So that matches with definition of contra variance, great:

# Best laid plans of mice
```scala
trait Stitcher[-T] extends Serializable {
  @uncheckedVariance
  def stitch(pieces: Iterable[(T, (Int, Int))]): T @uncheckedVariance 
}
// error: contravariant type T occurs in covariant position in type (pieces: Iterable[(T, (Int, Int))])T of method stitch
//         def stitch(pieces: Iterable[(T, (Int, Int))]): T
```

To be clear the covariant position is the return type.

Why is Scala angry? Lets break it down.

- We now can have `Stitcher[Tile]` when we asked for `Stitcher[IntArrayTile]`.
- We will use `stitch` method and give it instances of `IntArrayTile`... great.
  - again through Liskov substitution we can give a super-type in place of subtype
- `stitch` method will return an instance of `Tile` great ... except
  - We will think that it's an instance of `IntArrayTile`
  - really?

We obviously can't check if thats true with contra variance because scalac won't let us, but we can see what happens when do the same thing with covariant Box

```scala
cala> trait Box[+T] { def get: T }
defined trait Box

scala> val x: Box[Base] = new Box[Sub] { def get = new Sub }
x: Box[Base] = $anon$1@69930714

scala> x.get
res3: Base = Sub@3901d134
```

The return type of `Box.get` is bound to the type we have for the reference of Box, not the type that produced it. The variance rules are just there to make sure we don't shoot ourselves in the foot.

Treating an instance of `Tile` as `IntArrayTile` would be shooting ourselves in the foot. In reality it may be a different concrete subtype of `Tile`, type system says nothing about that.

# Escape Hatch
Actually, I'm not sure we can shoot ourselves in the foot here. This is the full implementation of `Stitcher[Tile]`

```scala
implicit object TileStitcher extends Stitcher[Tile] {
  def stitch(pieces: Iterable[(Tile, (Int, Int))], cols: Int, rows: Int): Tile = {
    val result = ArrayTile.empty(pieces.head._1.cellType, cols, rows)
    for((tile, (updateColMin, updateRowMin)) <- pieces) {
      result.update(updateColMin, updateRowMin, tile)
    }
    result
  }
}
```

If `ArrayTile.empty` could exactly reproduce the type of tile that we're working with the variance checking would be wrong and we could use this escape hatch:

```scala
import scala.annotation.unchecked._

trait Stitcher[-T] extends Serializable {
  def stitch(pieces: Iterable[(T, (Int, Int))]): T @uncheckedVariance
}
```

Sadly we can't do that because `ArrayTile.empty` doesn't cover all the mappings. We have:
- ArrayTile extends Tile
- CompositeTile extends Tile
- ConstantTile extends Tile
- CroppedTile extends Tile
- GeoTiffTile extends Tile with GeoTiffImageData
- LazyConvertedArrayTile extends Tile

If any of those were used as an input we'd be improperly casting some `ArrayTile` subtype to one of those other `Tile` subtypes, casting across type tree branches. No good.

# Type Hole

To skip a lot of meandering what we actually need is a mapping from the input type to return type that is somehow resolved at the call site.

First we solve the contra-variance signature problem:

```scala
trait StitcherR[T <: CellGrid, R <: CellGrid] extends Serializable {
  def stitch(pieces: Iterable[(T, (Int, Int))]): R
}

object StitcherR {
  implicit def tileStitcher[T <: Tile] = new StitcherR[T, Tile] {
    def stitch(pieces: Iterable[(T, (Int, Int))]): Tile = ???
  }
}

object Client {
  def needStitching[T <: CellGrid, R](pieces: T)(implicit stitcher: Stitcher[T, R]): R = {
    stitcher.stitch(pieces)
  }

  val pieces: Seq[IntArrayTile] = ???
  val res =  needStitching(pieces) // res will be given type of `Tile`
}
```

What appears to be happening here is:
- at call site `R` is totally unbound.
  - None of the function arguments provide any instances that would tie it down.
- `T` is bound to type of `pieces`.
- Scala goes a-looking for a Stitcher type class, finds an instance of it from `tileStitcher`
  - result of `tileStitcher` satisfies constraints on `T`, Scala grabs it.
- But wait, discovered instance of `Stitcher[T, R]` does specify `R` since it's actually an instance
- `R` from instance of`Stitcher[T, R]` is bound to `R` in `needStitching` and is used as result type

`R` is a ... type hole(?) that gets filled during the implicit resolution process.

**Comment by lossyrob** [comment]
We decided to not worry about subtypes having the Stitcher et al functionality. If you have an Int Array tile and want to stitch it, you will have to upcast it to a Tile and get a Tile back.
