### ISSUE TITLE
Kryo serializer versions

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis#1305]
We use `"de.javakaffee" % "kryo-serializers" % "0.27"` dep with the `kryo 2.24.0`, though in `spark-core 1.5.2` and in `Spark 1.5.2` default installer used `kryo 2.21.0`. This leads to problems with `GeoTrellis` usage in a spark cluster as a separate application (I mean app not launched via `spark-submit`) due to different `kryo serializer` versions on a client node. 

Current workaround for this issue: 

```scala
val geotrellisSpark  = "com.azavea.geotrellis" %% "geotrellis-spark" % Version.geotrellis exclude("com.esotericsoftware.kryo", "kryo")
val kryo             = "com.esotericsoftware.kryo" % "kryo" % "2.21"
```

The correct approach is to use `javakaffee 0.24`: http://mvnrepository.com/artifact/de.javakaffee/kryo-serializers/0.24

**Comment by pomadchin** [comment]
We have the following class registred: https://github.com/pomadchin/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/hadoop/KryoRegistrator.scala#L42 In the `0.24` lib version `de.javakaffee.kryoserializers.jodatime.JodaIntervalSerializer` not implemented

**Comment by jamesmcclain** [comment]
I tried commenting out the line
```scala
kryo.register(classOf[org.joda.time.Interval], new jodatime.JodaIntervalSerializer)
```
in `KryoRegister.scala` on my #1308 branch and running the tests in the `spark` project.  They succeeded without that line.

**Comment by pomadchin** [comment]
There is also an issue, Spark team plans to upgrade kryo version: https://issues.apache.org/jira/browse/SPARK-11416

**Comment by pomadchin** [comment]
Fixed (we moved to Spark 2), and we are not going to use `de.javakaffee` after moving to Java 8 time.
