### ISSUE TITLE
Dynamic partition sizing with S3InputFormat

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis#1313]
Currently we require user to provide `maxKeys` argument to limit the number of keys per partition. By default we use the AWS default of 1000 keys.

However, since we have to do the listing on the master and the size of the object is part of the object listing we should be able to do a smart thing and produce partition list based on the record size. They should be limited to contain something like 512MB,1024MB  or at least one record. There should be some testing to determine the optimal partition sizing.

**Comment by pomadchin** [comment]
:+1:
