### ISSUE TITLE
Vectorize Issue

### ISSUE THREAD

**Issue by kagoentzel** [geotrellis/geotrellis#1361]
In some circumstances when vectorizing an Array Tile the Polygon class will throw an error that it cannot cast type Multipolygon to Polygon around line 70.  The line that is failing is **p.buffer(0).asInstanceOf[jts.Polygon]**

I grabbed the source modified it to this instead: 
**val buff = p.buffer(0)
      if(buff.getGeometryType() == "MultiPolygon"){
        val t = "test"
        buff.asInstanceOf[jts.MultiPolygon].head
      }
      else{
        buff.asInstanceOf[jts.Polygon] 
      }**

That fixed that error but left incomplete polygons I added a couple methods in my copy to always vectorize to multipolygons, leaving the original so it wouldn't break anything .  This added code to the Multipolygon and Vectorize and VectorizeMethods.

**Comment by lossyrob** [comment]
This seems related to #1350. I have test data for that case, if you have a raster that I can test against, I'm going to be looking into Vectorization bugs tomorrow or early next week. Thank you!

**Comment by kagoentzel** [comment]
Hey Rob,

I am doing some process on the image up to that point.  I have attached the files Im using a geotiff and some geojson.  The scala code I’m using to generate the error is below.






Keith Goentzel | Senior Software Engineer | Swova 
m.  913.800.1764 | e. keith@swova.com <mailto:keith@swova.com> | w. www.swova.com <http://www.swova.com/>

**Comment by lossyrob** [comment]
Hey @kagoentzel,

The attachment doesn't come through on the github issue. Would you mind putting the attachments on something like google code and pasting the links here?

**Comment by kagoentzel** [comment]
Hey Rob,

The files are here.  http://web.swova.com/geotrellis/ <http://web.swova.com/geotrellis/>  

Let me know if there is anything I can do to help.

Thanks,

Keith

Keith Goentzel | Senior Software Engineer | Swova 
m.  913.800.1764 | e. keith@swova.com <mailto:keith@swova.com> | w. www.swova.com <http://www.swova.com/>
