### ISSUE TITLE
Remove S3 Layer Caching

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis#1372]
Currently `S3LayerReader` offers some caching functionality as an argument `getCache: Option[LayerId => Cache[Long, Array[Byte]]] = None`. The intent was to provide on disk cache for the S3 client, which is the most expensive of the clients.

However, this feature has not been used because of concerns of unbounded cache overruns. Further if layer readers are to have a cache options it should apply equally across all types of readers.

For the moment it is likely best to remove this features until can be integrated more fully into the API.

**Comment by lossyrob** [comment]
Fixed.
