### ISSUE TITLE
Update geotrellis.slick to slick 3.1

### ISSUE THREAD

**Issue by adamkozuch** [geotrellis/geotrellis#1383]
I created an issue just to separate it from docs issue. 
It would demand some changes:
1. Replace completely code in PostGisExtensions to newer one in https://github.com/tminglei/slick-pg/blob/master/core/src/main/scala/com/github/tminglei/slickpg/geom/PgPostGISExtensions.scala
2. Small changes in PostGisProjectionSupport and PostGisSupport (also based on slick-pg) 
3. Update tests
Is that correct?

**Comment by lossyrob** [comment]
@adamkozuch correct, your totally on the right track. Thank you!

**Comment by lossyrob** [comment]
Closed by  #1479
