### ISSUE TITLE
HBase Support

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis#1399]
GeoTrellis currently supports Apache Accumulo as a backends to store and retrieve raster data across a cluster and perofm multi-dimensional bounding box queries. Apache HBase is another open source distributed database that is very popular and well support by the open source community. 

We are looking to provide more deployment options and support HBase as a GeoTrellis backend for those interested in using GeoTrellis. The design of HBase and Accumulo is conceptually similar as they are both modeled after Google's BigTable, many of the lessons learned on Accumulo will be directly transferable to HBase.

**Comment by pomadchin** [comment]
Fixed in #1586 and can be closed @lossyrob @echeipesh @rossbernet. BTW HBase support was not mentioned in our twitter!
