### ISSUE TITLE
spark-notebook web map to view TileLayerRDD[SpatialKey]

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis#1401]
[spark-notebook](https://github.com/andypetrella/spark-notebook) is an web-based interactive REPL for Scala and Spark. Working in an interactive notebook is an effective strategy for exploration and custom analysis often employed by data scientists.

However when working on geospatial problem in spark-notebook there is no way to inspect the results of RDD operation that contains a tiled map layer. A desired solution is to produce a web map widget that would allow the user to visually explore the contents of a TileLayerRDD[SpatialKey]. Once this basic features is available dynamic resampling needs to be implemented to allow users to zoom in and out of the layer. 

This task will require working in both JavaScript and Spark/Scala and will produce a valuable feature for both scientists and compelling demos.

**Comment by lossyrob** [comment]
Using Jupyter for this problem is on the roadmap for 1.1. Closing this.
