### ISSUE TITLE
TileLayerRDD Metadata API Issue

### ISSUE THREAD

**Issue by jamesmcclain** [geotrellis/geotrellis#1405]
At present, if one tries to compile code similar to this:
```scala
val (mtl, geoTiff) = readBands(image, bands)
val ingestElement = (TemporalProjectedExtent(geoTiff.extent, geoTiff.crs, mtl.dateTime), geoTiff.tile)
val sourceTile = sc.parallelize(Seq(ingestElement))
val (_, metadata) =
TileLayerMetadata.fromRdd(sourceTile, FloatingLayoutScheme(512))
```

the result will be an unhelpful compiler error message that generally points to the fact that there is ambiguity in resolving the first context bound in this signature
```scala
def fromRdd[
  K: Component[?, ProjectedExtent]: (? => TilerKeyMethods[K, K2]),
  V <: CellGrid,
  K2: SpatialComponent: Boundable
](rdd: RDD[(K, V)], scheme: LayoutScheme)
```

The solution to the problem is to provide explicit type arguments:
```scala
TileLayerMetadata.fromRdd[TemporalProjectedExtent, MultibandTile, SpaceTimeKey](sourceTile, FloatingLayoutScheme(512))
```

Rather than have to do that, it would be nice to be able to write code like this:
```scala
val (_, metadata) = sourceTile.collectMetadata[SpaceTimeKey](FloatingLayoutScheme(512))
```

Tag: @lossyrob

**Comment by fosskers** [comment]
Feeling a similar pain at the moment.

**Comment by jamesmcclain** [comment]
I feel your pain.

**Comment by echeipesh** [comment]
Relevant to the issue: https://github.com/geotrellis/geotrellis/blob/3b132fdc0dd0ba4ca1e029e08d5c248e60846968/spark/src/main/scala/geotrellis/spark/package.scala#L174-L194
