### ISSUE TITLE
Ingest tiles without CRS in metadata

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis#1414]
We can have situation with wrong or incomplete GeoTiff tags. Some times there could be tiffs without crs. Probably we can add `source crs` param to `ETL` and `Ingest` objects to fix that issue.

**Comment by lossyrob** [comment]
@pomadchin do you think it would be possible to get this change into 1.0?

**Comment by pomadchin** [comment]
@lossyrob think yes
