### ISSUE TITLE
documents about use geotrellis in spark

### ISSUE THREAD

**Issue by wsf1990** [geotrellis/geotrellis#1440]
hello, I'm a new user. Dose anyone know or have any documents about how to use geotrellis in spark?Can you help me? 
many thanks!

**Comment by pomadchin** [comment]
Hi! 
We have a documentation folder [there](https://github.com/pomadchin/geotrellis/tree/master/docs). I can recommend you to start [here (etl process description)](https://github.com/pomadchin/geotrellis/blob/master/docs/spark-etl/spark-etl-intro.md). More certain questions are appreciated, + we use our [gitter channel](https://gitter.im/geotrellis/geotrellis),where your all possible questions can be answered real time.

**Comment by wsf1990** [comment]
dose you have a document like_** get start**_?
