### ISSUE TITLE
layoutScheme tms and floating

### ISSUE THREAD

**Issue by wsf1990** [geotrellis/geotrellis#1453]
When ingest data use spark-etl,the arg about layoutScheme  have two selection tms and floating,dose any body konw the difference between tms and floating and how to use them?
Thanks!

**Comment by pomadchin** [comment]
`Tms` is a [common zoomed layout scheme](https://wiki.osgeo.org/wiki/Tile_Map_Service_Specification), it is possible to specify tile sizes and the desired projection for that scheme (input tiles would be reprojected and tiled according to scheme).

`Floating` is a layout scheme in the input files projection, without zooming (that's a way to load tiles in the input resolution with maximum quality loss and in the input crs, but tiled). It is possible to define only tile sizes for that scheme.

**Comment by wsf1990** [comment]
Thanks! But when I ingest the data use floating, and read the tile use the same method as floating,I cant get the tile,it shows error that cant read the layer at the zoom.Why?

**Comment by pomadchin** [comment]
@wsf1990 it loads as 0 zoom level

**Comment by wsf1990** [comment]
Thanks for your patients!
But I have a new question.I made a object which is **TileLayerRDD[SpatialKey]**,Dose Geotrellis have some method can make this object to geotiff?
Thanks!

**Comment by pomadchin** [comment]
Yes. So this RDD represents a set of pairs `(SpatialKey, Tile)`. To save it as geotiff, we have to stitch these tiles, and save as geotiff file: 

```scala
val rdd: TileLayerRDD[SpatialKey] = ???
val destDir = ??? // destination dir to save geotiff
val crs: CRS = ??? // geotiff crs
GeoTiff(rdd.stitch, crs).write(dir)
```

**Comment by wsf1990** [comment]
When I use this method,I got the tif,But Why the data of the tif all is 0?I checked the tile,It has data,some was 0 and mang great than 255,like 1600?Cant the data great than 255?

**Comment by pomadchin** [comment]
What's the tiff metadata? How did you ingest it, using etl? What's tiff metadata (using gdal of original tiff / of the ingested tiff (layer metadata))?

**Comment by wsf1990** [comment]
yes,using etl,Its the data of dem.And I try to set the tile's data to 0 -255 use this method
val tilemap = r.stitch.tile.map(s => Random.nextInt(255))
can get the right tif.Cant the tile data great than 255

**Comment by wsf1990** [comment]
Or has some other options need to set?

**Comment by wsf1990** [comment]
I got the reason.Because the geotiff dosent set the nodata value?Is it any method can set the NODATA value of geotiff.

**Comment by wsf1990** [comment]
I use this method 
`val tilemap = r.stitch.tile.map(s => if(s == 0) NODATA else s)
    tilemap.foreach((s1) =>{
              println(s1)
          })`
But the result dosent change,0 havent been changed to NODATA

**Comment by pomadchin** [comment]
What is the tile type? (`tile.cellType`) 
Each tile type has it's own `NoData` value, + each can has a custom `NoData` value, [here](https://github.com/geotrellis/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/CellType.scala) you can find all types avail.

**Comment by wsf1990** [comment]
yes,the data type was int16,and I use shortNODATA,But the geotiff has many -32768,Dose this some method can set the geotiff's NODATA value in the metadata?
When we use gdalInfo see some geotiff's infomation,Their has one metadata info is NoData Value.

**Comment by wsf1990** [comment]
I have resolved this problem,My data's CellType is ShortCellType,So the geotiff dont have NoData MetaData,When I convert it to ShortConstantNoDataCellType,the Geotiff added the NoData MetaData.
I must read Geotrellis source code carefully!
Thanks!
