### ISSUE TITLE
Kernel Density Operation on Spark

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis#1456]
We would will have a Kernel Density operation on spark something that takes form of:
`(RDD[PointFeature[Int]], LayoutDefinition) => RDD[(SpatialKey, Tile) with Metadata[TileLayerMatadata[SpatialKey]]`

We already have some code that supports such an operation for a single tile: https://github.com/geotrellis/geotrellis/blob/2402607b0c6f5a4e087bc46fe32c5f56e206947e/raster/src/main/scala/geotrellis/raster/VectorToRaster.scala#L49-L76

Conceptually to distribute this operation we're going to have to assign each point to a set of tiles that it can contribute any values to, then perform a shuffle and burn the points into the tiles.

A likely progression of tasks is:
### test covering out of tile points
We're going to have to stamp points which are outside of the raster boundaries, those points that are close enough to influence a specific tile. This case is not covered in our unit tests and while it looks like it should be supported, it needs to be covered explicitly now. A good test would be that a tile layout of tiles stamped with a set of points when `stitched` together are equal to a single tile of combined size stamped with those same points.

### test to guide RDD implementation
A good test would be to do a similar thing, where an `RDD[Raster[Tile]` is generated by burning every point into every tile, even if the point can not possibly contribute to that tile and comparing the result to the actual kernel density function that makes the join more efficient by dropping such points.

### implement Kernel Density
Implement the efficient join of points and conversion to Tiles via kernel density. 

### Double Kernel Density
Currently the operation can only produce raster of type Int. It and all consuming operations need to be expanded to be able to produce tiles of any CellType.

**Comment by pomadchin** [comment]
Closed in https://github.com/geotrellis/geotrellis/pull/1469, @echeipesh @lossyrob @rossbernet.

**Comment by pomadchin** [comment]
Fixed by @jpolchlo can be closed @echeipesh @lossyrob @rossbernet.

**Comment by echeipesh** [comment]
Implemented by: https://github.com/geotrellis/geotrellis/pull/1469

**Comment by echeipesh** [comment]
Implemented by: https://github.com/geotrellis/geotrellis/pull/1469
