### ISSUE TITLE
Regression in classBreaks?

### ISSUE THREAD

**Issue by RickMohr** [geotrellis/geotrellis#1462]
With 0.10.0-RC3 (and previous versions) a `classBreaks` call on test data returned
```
[346600,449400,542600,613000,688800,792800,902800,1148600,1571800,2000002]
```
With 0.10.0 the same call on the same data returns
```
[-2147483648,-2147483648,-2147483648,-2147483648,116075,434547,610418,788548,1172822,2000002]
```
Looks like it's including NODATA values?

The call is here: https://github.com/OpenTreeMap/otm-modeling/blob/6d8c63c4c756f07adb7f6995c776d4e7e18cd8bb/tile/src/main/scala/TileService.scala#L97

(`model` has type `TileLayerRDD[SpatialKey]`)

**Comment by RickMohr** [comment]
I note that `gdalinfo` reports the dataset's NODATA value as 2147483647 (hex 7FFF FFFF) but the returned breaks contain -2147483648 (hex 8000 0000). 

`breaks(0) == NODATA` is true

**Comment by RickMohr** [comment]
The S3 dataset is `azavea-datahub/catalog/us-census-property-value-tms-epsg3857`

**Comment by RickMohr** [comment]
It works if I use
```
                val breaks = model.histogramExactInt.quantileBreaks(numBreaks)
```
instead of 
```
                val breaks = model.classBreaks(numBreaks)
```
Did ecdbfabd463bf40d027a3456a3ff45d6060b061 cause it to look for a `Double`NODATA value instead of an `Int` NODATA value?

**Comment by lossyrob** [comment]
It should do the translation correctly from Int NODATA to Double NODATA.

What is the cell type of the tiles?
Is this a layer that was ingested in a pre-0.10 RC process? My current guess is that we changed the layer metadata celltype, but the celltype of the tiles are being read in as raw (not containing any specified NoData value) data type. So the Int.MinValue values are being considered as valid raw values. However when it's passed through the integer-based functions, it matches the constant NODATA and so it is being treated as a correct NoData value by those functions.

The hacky fix here would be to do a `.convert(IntConstantNoDataCellType)` on the layer before calling classBreaks.

**Comment by RickMohr** [comment]
Yes, the (`int32`) data was ingested pre-0.10 RC. The ingest was done by https://github.com/azavea/azavea-data-hub/blob/master/etl/ingest/jobs/census-property-value.sh which purportedly set the metadata value correctly. But other evidence in addition to your suspicion suggests it did not.

Sounds like the right solution is to re-ingest the data, preserving the NODATA metadata.

**Comment by lossyrob** [comment]
Yes, unfortunately the proper fix would be a re-ingest.

**Comment by RickMohr** [comment]
Need to do that anyway to have proper metadata. Thanks.

**Comment by RickMohr** [comment]
I re-ingested the data (with proper NODATA metadata) but the problem is still there.

I see it in 5 different datasets, all ingested with proper NODATA metadata. Summary in this spreadsheet:

https://docs.google.com/a/azavea.com/spreadsheets/d/1n-h3oCaq1vyZsnwg8iycV6O3pTIYEk5_xQGs-KobYgo/edit?usp=sharing

**Comment by RickMohr** [comment]
I tried `convert` using the NODATA values that are actually in the datasets.
```scala
if (model.metadata.cellType == IntCellType) {
  breaks = model.convert(IntUserDefinedNoDataCellType(2147483647)).classBreaks(numBreaks)
} else if (model.metadata.cellType == FloatCellType) {
  breaks = model.convert(FloatUserDefinedNoDataCellType(-2)).classBreaks(numBreaks)
} else if (model.metadata.cellType == ByteCellType) {
  breaks = model.convert(ByteUserDefinedNoDataCellType(127)).classBreaks(numBreaks)
}
```
That succeeds for datasets with `IntCellType` and `ByteCellType` (some ingested with GT 0.10.0 and some with pre-RC versions) but fails for datasets with `FloatCellType` (some ingested with GT 0.10.0 and some with pre-RC versions)

**Comment by lossyrob** [comment]
Interesting thing is, if the ingest script set the cell type to "int32", then the ingested tiles should not be `IntCellType`, but `IntConstantNoDataCellType` (as can be reasoned about here https://github.com/geotrellis/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/CellType.scala#L290

**Comment by RickMohr** [comment]
I agree it seems like something isn't right with the NODATA values. But the ingest script sure seems to be setting `int32` https://github.com/RickMohr/azavea-data-hub/blob/new-otm-scripts/etl/ingest/jobs/census-property-value.sh#L6

**Comment by RickMohr** [comment]
JSON metadata shows `"cellType":"int32"`
(`metadata__us-census-property-value-30m-epsg3857__12.json` in https://console.aws.amazon.com/s3/home?region=us-east-1#&bucket=azavea-datahub&prefix=catalog/_attributes/

**Comment by lossyrob** [comment]
`int32` translates to `IntConstantNoDataCellType`, but it is seeming like somehow the tile cell type is set to `IntCellType`, which has no NoData value. That seems to be the problem...will have to pull some info from the tiles to check.

**Comment by RickMohr** [comment]
I've fixed the errors in our code. Integer and Byte datasets are working but Float datasets are not.

More specifically:
* For a dataset with cell type `IntConstantNoDataCellType` (or `UByteConstantNoDataCellType` converted to `IntConstantNoDataCellType`), both `classBreaks` and `classBreaksExactInt` correctly ignore `NoData` values.
* For a dataset with cell type `FloatConstantNoDataCellType`,
`classBreaksExactInt` correctly ignores `NoData` values but `classBreaks` does not. Converting to `FloatUserDefinedNoDataCellType` worked for a dataset with `NoData` value `-2` but not for one with `NoData` value `-3.40E38`.

Spreadsheet updated with actual code and results:
https://docs.google.com/spreadsheets/d/1n-h3oCaq1vyZsnwg8iycV6O3pTIYEk5_xQGs-KobYgo
