### ISSUE TITLE
Provide a sampling parameter to histogram method of StatsTileRDDMethods

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1465]
For summary methods off of StatsTileRDDMethods that create a StreamingHistogram, we don't necessarily need to sample all of the tiles. There should be a parameter that includes a sample percentage, to allow the user to speed up performance by only sampling a subset of the tiles. This idea comes from @jamesmcclain

**Comment by lossyrob** [comment]
This can work if you just use the `sample` method on an rdd, e.g.

```scala
rdd,sample(0.1).histogram
````
(Not clear this is the actual syntax)

We should make sure this works fine and document it in the spark-examples

**Comment by echeipesh** [comment]
https://github.com/apache/spark/blob/39755169fb5bb07332eef263b4c18ede1528812d/core/src/main/scala/org/apache/spark/rdd/RDD.scala#L465-L489
