### ISSUE TITLE
Move spark testfiles to testkit

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1467]
We don't use actual files anymore for spark tests, and instead generate the data. This is something that might be useful to other users, and we should move it to `geotrellis-spark-testkit`.

https://github.com/geotrellis/geotrellis/blob/241b353a1b8e3a43a3a1277f19232a7a338388f1/spark/src/test/scala/geotrellis/spark/testfiles/TestFiles.scala

Resolving this issue also includes going over the spark test project and making sure any generalized test data generation moves over to testkit.

**Comment by pomadchin** [comment]
Fixed by @echeipesh in #1266 and can be closed @lossyrob @echeipesh @rossbernet.
