### ISSUE TITLE
How to find a tile that intersects a point in TileLayerRDD

### ISSUE THREAD

**Issue by wsf1990** [geotrellis/geotrellis#1470]
How can I get a point's data In an object like this 
`RDD[(SpatialKey, Tile)] with Metadata[TileLayerMetadata[SpatialKey]]`
thanks!

**Comment by lossyrob** [comment]
Do you just want one point? It would be better to get the single tile using a `ValueReader` instead of a whole RDD. But if you need to have the whole RDD, then I would do:

```scala
val point: Point = ???
val layer: RDD[(SpatialKey, Tile)] with Metadata[TileLayerMetadata[SpatialKey]] = ???

val key = layer.metadata.mapTransform(point)
val dataValues: Seq[Double] =
  layer
    .asRasters // Converts the tiles to rasters
    .lookup(key) // Looks up any rasters that are of the specified key
    .map(_.getDoubleValueAtPoint(point))
```

Now `dataValues` holds the value of any of the tiles that contained that point. If there are no tiles, the Seq will be empty; if there were multiple tiles with the same key, there will be multiple points.

**Comment by wsf1990** [comment]
Many Thanks！
Can you tell me how to use ValueReader to get the point's data?
I had ingest the tiff data to Accumulo.

**Comment by wsf1990** [comment]
Now I can use AccumuloValueReader get the tile which contains the point.
But how can I get the _col, row_ which is the offset of the point in the tile?

**Comment by pomadchin** [comment]
@wsf1990 actually, you can get key bounds range from layer metadata: 

```scala
val instance: AccumuloInstance = ???
val layerId: LayerId = ???

val attributeStore = AccumuloAttributeStore(instance)
val keyBounds = attributeStore.readMetadata[TileLayerMetadata[SpatialKey]](layerId).bounds // SpaceTimeKey for space time ingest
```

**Comment by echeipesh** [comment]
@wsf1990 sounds like your question is resolved, so I am going to close this issue. If you have more questions please drop by our Gitter channel: https://gitter.im/geotrellis/geotrellis
