### ISSUE TITLE
Fix the "WithCrs" API in geotrellis.vector.io.json

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1475]
Currently we have a `geotrellis.vector.io.json.Crs` trait, with some decedents, and a `WithCrs` case class. It's what allows us to work with GeoJson that has a `crs` field. It's bad in that it conflicts with the `geotrellis.proj4.CRS` type, and also the API could be improved. This task is about making that API better.

**Comment by pomadchin** [comment]
Fixed by @echeipesh in #1266 and can be closed @lossyrob @echeipesh @rossbernet.
