### ISSUE TITLE
Optimize ColorMap rendering by implementing binary search or similar

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1489]
Currently the color map find the correct color to map to by iterating through the class break values in sequence and stopping once it finds the appropriate value. This could be optimized by using a b-tree, or something similar, to search for the nearest class break. Potentially the tree could be weighted towards more likely values if a histogram is involved.

**Comment by fosskers** [comment]
Taking a look.

**Comment by fosskers** [comment]
`IntColorMap.map`:

```scala
   def map(z: Int) = {
     if(isNoData(z)) { options.noDataColor }
     else {
       var i = 0
       while(i < len && zCheck(z, i)) { i += 1 }
       if(i == len){
         if(options.strict) {
           sys.error(s"Value $z did not have an associated color and break")
         } else {
           options.fallbackColor
         }
       } else {
         orderedColors(i)
       }
     }
   }
```
