### ISSUE TITLE
StreamingHistogram numbuckets argument unused

### ISSUE THREAD

**Issue by moradology** [geotrellis/geotrellis#1497]
Calls to the `histogram` methods which end up using the StreamingHistogram variant don't seem to be able to change the number of buckets as it seems they should:
You can see the default set to 80 here:
https://github.com/geotrellis/geotrellis/blob/48162b824df222afbd75c6495fa1e4bc00344fd9/raster/src/main/scala/geotrellis/raster/histogram/StreamingHistogram.scala#L37

And what seems like a method which should allow setting an alternative bucket count:
https://github.com/geotrellis/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/summary/SummaryMethods.scala#L32

**Comment by lossyrob** [comment]
That method should be doing the thing that it purports to do, and set the bucket count on the histogram.

**Comment by moradology** [comment]
closing
