### ISSUE TITLE
ArrayTile.empty doesn't initialize cells to user-defined NODATA value

### ISSUE THREAD

**Issue by RickMohr** [geotrellis/geotrellis#1503]
```scala
scala> val t = ArrayTile.empty(IntUserDefinedNoDataCellType(99), 1, 2)
t: geotrellis.raster.MutableArrayTile = IntUserDefinedNoDataArrayTile([I@c0ece5,1,2,int32ud99)

scala> t.get(0,0)
res15: Int = -2147483648
```

The cell's value should be 99

**Comment by lossyrob** [comment]
@RickMohr this is the expected result.

All of `get`, `map` etc (and on the double side, `getDouble`, `mapDouble` etc) use NODATA (or Double.NaN) to represent NoData values, no matter what the tile's internal representation of NoData is. So there is a translation happening between the internal NoData value (99) and the "external" standard NoData value (Int.MinValue, or NODATA).

If you want to just fill a Tile with the value 99, you can use:
```scala
val t = ArrayTile.fill(99, 1, 2)
```

Perhaps the docs should be better at explaining this difference between internal vs external NoData values. Do you have a suggestion of where that information could go (perhaps someplace you looked before posting this bug)?

**Comment by RickMohr** [comment]
I've posted some ideas for NODATA documentation in #1508.
