### ISSUE TITLE
ColorMap.render ignores NODATA value defined by input tile's cell type

### ISSUE THREAD

**Issue by RickMohr** [geotrellis/geotrellis#1504]
When `ColorMap.render` detects whether an input cell value is NODATA, the input tile's cell type is ignored. For example, cell values of -2147483648 are treated as NODATA regardless of whether the tile's cell type is `IntCellType`, `IntConstantNoDataCellType`,  or `IntUserDefinedNoDataCellType(99)`.

**Comment by lossyrob** [comment]
This is due to the fact we are using a constant as a marker for the "external" NoData value. The hope was that `Int.MinValue` is such an esoteric number that you would never catch it in the wild when it didn't actually mean NODATA. So, this is expected behavior. Is there a situation where this is causing problems?

**Comment by RickMohr** [comment]
A subtle bug was harder to diagnose because of this. My input tile mistakenly had `IntCellType` instead of `IntConstantNoDataCellType`, which would have been obvious if its cells with -2147483648 were treated as data instead of NODATA.

**Comment by RickMohr** [comment]
The root of that subtle problem, by the way, is that `ColorMap.render` outputs an `IntCellType` tile. Since `ColorMap` is NODATA-aware I would have expected the cell type to be `IntUserDefinedNoDataCellType(options.noDataColor)` (or by default `IntUserDefinedNoDataCellType(0)`.

**Comment by RickMohr** [comment]
Note that these issues wouldn't have come up if I were using `ColorMap.render` to create a raster of colors. Instead I was using it to transform cell values. A `ValueMap` class would likely behave more conventionally wrt NODATA values.

**Comment by lossyrob** [comment]
True, I think a ValueMap would be useful. Perhaps we should close this issue out and make one for creating a ValueMap?

**Comment by RickMohr** [comment]
Good idea, closing in favor of #1509.
