### ISSUE TITLE
Multiband foreach method that gives all band values

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1530]
`MultibandTile` needs methods with the signature:

```scala
def foreach(f: Array[Int] => Unit): Unit
def forachDouble(f: Array[Double] => Unit): Unit
```

That will allow the user to pass in a method that receives all band values fore each pixel in sequence as an array (where arr(0) is the 0-index band's value, arr(1) is the 1-index band's value, etc) and calls that for each pixel.

**Comment by hjaekel** [comment]
I created a pull request for this issue. It includes the implementation as discussed in the Gitter chat and some unit tests.

**Comment by pomadchin** [comment]
Fixed by @hjaekel, can be closed @lossyrob @echeipesh @rossbernet.
