### ISSUE TITLE
Spark ETL: support clipping to a specified extent

### ISSUE THREAD

**Issue by RickMohr** [geotrellis/geotrellis#1547]
For situations where you're ingesting a large raster but don't need the whole thing it would be useful to specify an extent (in the target CRS) and receive clipped output.

**Comment by lossyrob** [comment]
This would require adding a new option, e.g. `--clip xmix,ymin,xmax,ymax`, to ETL. Simple would filter the source RDD by that extent; I don't think we'd need to mask to the exact incoming extent, but we could do that potentially per tile in the source RDD.

There is some refactoring going on to ETL, so we'll wait on this feature until we implement the json-config-based ETL, unless someone is hot for this feature and feels like coding it up.

**Comment by fosskers** [comment]
@pomadchin it's probably possible to tackle this now that we have the JSON-based ETL.

**Comment by pomadchin** [comment]
@fosskers planning to take it on Monday and to make a single pr with all etl updates
