### ISSUE TITLE
Single Raster ingest using Filewriter renders as disjoint blocks

### ISSUE THREAD

**Issue by owcm** [geotrellis/geotrellis#1576]
Experienced this problem with customer supplied Geotiff and ingesting with HadoopLayerWriter.  Was able to recreate using modified geotrellis-landsat-tutorial project added git project at https://github.com/owcm/demo-of-raster-ingest-issue.

File is ingested with FileWriter and when rendered no data for the cached Avro data is displayed until you zoom to level 13, then random blocks of the ingested file are rendered.

Rob Emanuele: Recommended work around in IngestImage.scala file changing:

 val inputRdd: RDD[(ProjectedExtent, Tile)] =
      sc.hadoopGeoTiffRDD(inputPath)

to 

 val inputRdd: RDD[(ProjectedExtent, Tile)] =
      sc.hadoopGeoTiffRDD(inputPath).mapValues { tile => tile.convert(FloatConstantNoDataCellType) }

This modification allowed the Geotiff to be ingested and then rendered correctly but points to underlying problem.

Contents of Readme:
This project is a modified version of the Geotrellis-Landsat-Tutorial used to demonstrate a bug with processing a particular Geotiff file that was read correctly by gdal and QGIS.

The IngestImage and ServeNDVI files where modified to deal with Single Tile .vs. Multiband Tile. The ServeNDVI was modified to do a simple aspect operation on the ingested tile.

To receate clone this project and download the file cf8b850a-c3fb-4596-ac46-f553c216078f-1.tif using the link https://drive.google.com/file/d/0B1YZbN2gCsmSYV9YbkJnaWNrYTA/view 
Copy the file to the data directory in the project.

Then sbt run:

Select option 2 to Ingest the Image.

sbt run again:

Select option 4 to run the server.

Server runs on port 8090. Run index.html to see random blocks being displayed for ingested Geotiff.

**Comment by lossyrob** [comment]
Given the raster, this code exhibits the issue:

```scala
import geotrellis.spark._
import geotrellis.spark.io._
import geotrellis.spark.io.hadoop._
import geotrellis.spark.util._
import geotrellis.raster.resample._
import geotrellis.raster.io.geotiff._

implicit val sc = SparkUtils.createLocalSparkContext("local[*]","asdf")
val rdd = sc.hadoopGeoTiffRDD("owcm-wm.tif")
val rdd2 = rdd.split(1024, 1024)
val (_, rasterMetaData) = TileLayerMetadata.fromRdd(rdd2, FloatingLayoutScheme(512))
val rdd3 = rdd2.tileToLayout(rasterMetaData.cellType, rasterMetaData.layout, Bilinear)
val raster = ContextRDD(rdd3.repartition(100), rasterMetaData).stitch
val crs = rasterMetaData.crs
GeoTiff(raster, crs).write("went-through-rdd.tif")
```

While if we map to a new tile type, we see it disappear:

```scala
import geotrellis.spark._
import geotrellis.spark.io._
import geotrellis.spark.io.hadoop._
import geotrellis.spark.util._
import geotrellis.raster.resample._
import geotrellis.raster.io.geotiff._

implicit val sc = SparkUtils.createLocalSparkContext("local[*]","asdf")
val rdd = 
  sc.hadoopGeoTiffRDD("owcm-wm.tif")
    .mapValues { tile => tile.convert(FloatConstantNoDataCellType) }
val rdd2 = rdd.split(1024, 1024)
val (_, rasterMetaData) = TileLayerMetadata.fromRdd(rdd2, FloatingLayoutScheme(512))
val rdd3 = rdd2.tileToLayout(rasterMetaData.cellType, rasterMetaData.layout, Bilinear)
val raster = ContextRDD(rdd3.repartition(100), rasterMetaData).stitch
val crs = rasterMetaData.crs
GeoTiff(raster, crs).write("went-through-rdd.tif")
```

**Comment by lossyrob** [comment]
@owcm can you verify that the original tile type is a raw type (with no defined NoData type)?

With Bilinear interpolation, it checks and handles NoData values specifically; if the tile does not have any NoData values, it considers any value as valid, and includes that in the interpolation. This can have dire consequences on tile merging. This is why switching the tile type to one that has a NoData value will produce the correct result.

**Comment by owcm** [comment]
@lossyrob using gdalinfo I confirmed that there is "NoData Value" defined.  The Type is Float32. Does that answer your question?

If a "NoData Value" is set should I artificially set one like -9999.  The { tile => tile.convert(FloatConstantNoDataCellType) } modification seems to solve the problem for me.

Chris

**Comment by lossyrob** [comment]
There is no nodata value set that I see:

```
Driver: GTiff/GeoTIFF
Files: /Users/rob/Downloads/cf8b850a-c3fb-4596-ac46-f553c216078f-1 (1).tif
Size is 7328, 10437
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (-76.055594392984787,36.952409419781539)
Pixel Size = (0.000004802292755,-0.000004802292755)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=DEFLATE
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -76.0555944,  36.9524094) ( 76d 3'20.14"W, 36d57' 8.67"N)
Lower Left  ( -76.0555944,  36.9022879) ( 76d 3'20.14"W, 36d54' 8.24"N)
Upper Right ( -76.0204032,  36.9524094) ( 76d 1'13.45"W, 36d57' 8.67"N)
Lower Right ( -76.0204032,  36.9022879) ( 76d 1'13.45"W, 36d54' 8.24"N)
Center      ( -76.0379988,  36.9273487) ( 76d 2'16.80"W, 36d55'38.46"N)
Band 1 Block=7328x1 Type=Float32, ColorInterp=Gray
```

The `{ tile => tile.convert(FloatConstantNoDataCellType) } ` simply converts the type to one with NoData, so this is the fix that is correct (other then modifying the original tiffs to include a nodata).

**Comment by owcm** [comment]
Yes, that was what I was seeing NO "NoData Value" defined for the image.  Sorry I was ambiguous on my previous response.

So I guess this can be closed, code is behaving as designed and there is a legit work around.

**Comment by lossyrob** [comment]
Great, closing. We need to document this behavior, but that will be addressed in a separate issue/PR. Thanks @owcm.
