### ISSUE TITLE
HadoopIngest not working with Spark standalone

### ISSUE THREAD

**Issue by lillythomas** [geotrellis/geotrellis#1579]
Hi,

I apologize for posting a second ticket in less than 24 hours, but I am trying to ingest a geotiff from my local file system using this code (https://gist.github.com/lossyrob/59f8116b07d37f7f45c5).  The only things changed were the input pathname and the layer name.  I am running the standalone version of spark and every time I execute the script, I encounter these errors:
`	zip warning: spark/target/scala-2.10/geotrellis-spark-assembly-0.10.0-SNAPSHOT.jar not found or empty
	zip warning: name not matched: META-INF/ECLIPSEF.RSA

zip error: Nothing to do! (spark/target/scala-2.10/geotrellis-spark-assembly-0.10.0-SNAPSHOT.jar)
	zip warning: spark/target/scala-2.10/geotrellis-spark-assembly-0.10.0-SNAPSHOT.jar not found or empty
	zip warning: name not matched: META-INF/ECLIPSEF.SF

zip error: Nothing to do! (spark/target/scala-2.10/geotrellis-spark-assembly-0.10.0-SNAPSHOT.jar)
Warning: Local jar /Users/lilliannethomas/geotrellis/spark/target/scala-2.10/geotrellis-spark-assembly-0.10.0-SNAPSHOT.jar does not exist, skipping.
java.lang.ClassNotFoundException: geotrellis.spark.ingest.HadoopIngestCommand
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:175)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:689)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)`

I saw that these errors have been discussed in [#1099](https://github.com/geotrellis/geotrellis/issues/1099), however the workaround seemed to require cassandra.  I would ideally like to not rebuild spark in order for this hadoopingest to work.  Is there anything I am missing or is this functionality simply not there yet?

Thanks so much in advance,
Lilly

**Comment by lossyrob** [comment]
Hey Lilly, 

First, no worries about posting issues quickly, the more the merrier. I or other team members will get to them as fast as we can.

That's a bit of an old gist. I would recommend using `spark-etl` for running an ingest on some GeoTiffs. Here's the docs for `spark-etl`:
https://github.com/geotrellis/geotrellis/blob/master/docs/spark-etl/spark-etl-intro.md
https://github.com/geotrellis/geotrellis/blob/master/docs/spark-etl/spark-etl-run-examples.md

The docs might be missing some things, or be a bit "starting from step 2 instead of step 1", so please let us know how to improve them if they are not clear.

Thanks,
Rob

**Comment by lillythomas** [comment]
Hey Rob,

Thanks again.  I really appreciate your patience!  So before I run a bash script containing:
 `#!/bin/sh
export JAR="geotrellis-etl-assembly-0.10-SNAPSHOT.jar"

spark-submit \
--class geotrellis.spark.etl.{SinglebandIngest | MultibandIngest} \
--master local[*] \
--driver-memory 2G \
$JAR \
--input hadoop  --format {geotiff | temporal-geotiff} --cache NONE -I path="file:///Data/nlcd/tiles" \
--output hadoop -O path="hdfs://geotrellis-ingest/nlcd/" \
--layer nlcd-tms --crs EPSG:3857 --pyramid --layoutScheme {tms | floating}`
will I need to run ./sbt "project spark" assembly? Every time I have tried to run that I encounter a flood of errors and it ultimately fails.  I would assume that my inability to run that command is causing the absence of the "geotrellis-etl-assembly-0.10-SNAPSHOT.jar" in the geotrellis/project/target/scala-2.10 directory.  

Not sure if these errors encountered after running the ./sbt "project spark" assembly command have anything to do with the fact that I have spark and hadoop installed independent of geotrellis elsewhere.  And I know that the geotrellis library is not being picked up when I try to import, for example geotrellis.raster._, into the spark-shell.  

Sorry if that was confusing.  I am really hoping to get in gear with geotrellis soon! 

Thanks again for your help,
Lilly

**Comment by lossyrob** [comment]
You'll need the `spark-etl` assembly. That's a different subproject, or module, that deals with ETL (Extract/Transform/Load) applications.

So you'll need to run `./sbt "project spark-etl" assembly`. Then change the `export JAR="..."` to point to that jar that was created (it's in the spark-etl/target/scala-2.10 folder). 

For that functionality to be available in the spark-shell, you'll have to point to that jar as well. Something like 

`spark-shell --jars [containing dir]/target/scala-2.10/[assembly jar]` e.g.
`spark-shell --jars /Users/rob/proj/gt/geotrellis/spark-etl/target/scala-2.10/geotrellis-spark-etl-assembly-1.0.0-SNAPSHOT.jar`

**Comment by fosskers** [comment]
@lillythomas did you solve your issues?

**Comment by pomadchin** [comment]
I believe this issue can be closed, and re-opened / or created some new (as API changed a lot) and discussed in our [gitter channel](https://gitter.im/geotrellis/geotrellis)
