### ISSUE TITLE
Remove warnings about deprecated macro functionality when compiling in 2.11

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1602]
Perhaps we could use https://github.com/milessabin/macro-compat for this?

**Comment by fosskers** [comment]
Are these the warnings you mean?

```console
[info] Because /home/colin/code/azavea/geotrellis/raster/src/main/scala/geotrellis/raster/BitArrayTile.scala contains a macro definition, the following dependencies are invalidated unconditionally:
```

**Comment by lossyrob** [comment]
No, it was the ones that talk about BlackBox vs WhiteBox macros.

I'm not sure what the one you posted means, but it would be good to track that down too

**Comment by fosskers** [comment]
An `sbt clean compile` on master gives:
 
- two pattern match exhaustion warnings
- one type eraser warning

And I can't find any other warnings about macros. Did the original issue fix itself?

**Comment by pomadchin** [comment]
@fosskers original issue was fixed it [there](https://github.com/geotrellis/geotrellis/pull/1628)

**Comment by fosskers** [comment]
You're right, so this can be closed @lossyrob .
