### ISSUE TITLE
`ContextRDD[K, Tile, M].polygonalMean` yields `null` when empty

### ISSUE THREAD

**Issue by fosskers** [geotrellis/geotrellis#1612]
#1611 relaxed the type constraints on `PolygonalSummaryTileLayerRDDMethods` such that any `RDD` containing `Tile`s and whose metadata has an implicit lens into a `LayoutDefinition` can now use the Polygonal Summary methods for free.

In using the changes in that patch, quite by accident I discovered that calling `polygonalMean` on an empty `RDD` returns `null`, which is not so nice for a Scala application. Here's the current implementation:

```scala
  def polygonalMean(polygon: Polygon): Double =
    polygonalSummary(polygon, MeanResult(0.0, 0L), MeanSummary).mean
```

which converts the RDD to rasters, then to features, and then calls:

```scala
def polygonalSummary[T: ClassTag](polygon: Polygon, zeroValue: T)(handler: PolygonalSummaryHandler[G, D, T]): T =
    featureRdd.aggregate(zeroValue)(handler.mergeOp(polygon, zeroValue), handler.combineOp)
```

Is `null` expected? While the sum of an empty list is 0, and then product of an empty list is 1, is there such an element value for the `mean` operation? The concensus in a recent standup was "no".

Adding `Option` here is nicer than `null`, but would mean an API change.

**Comment by fosskers** [comment]
It makes sense why `mean` has an undefined element value. If mean is the sum of all values divided by the quantity of them, then:

```scala
val sum = 0
val quantity = 0
val mean = sum / quantity  // java.lang.ArithmeticException: / by zero
```

**Comment by fosskers** [comment]
**Update:** With the current master, the various `polygonal*` methods produce the following results on an empty RDD:

```
MEAN: NaN
MAX: -2147483648
MIN: 2147483647
SUM: 0
```

I'd say only the `SUM` result is expected.

**Comment by fosskers** [comment]
The functional programmer in me wants to wrap functions with holes in their domain in `Option` and call it a day:

```scala
RDD.polygonalMean: Polygon => Option[Double]
RDD.polygonalMax: Polygon => Option[Int]
RDD.polygonalMin: Polygon => Option[Int]
```
Technically `mean` `max` and `min` are proper functions without holes in their domains, since `RDD.empty` maps to something here, however:

- Mathematically, -2147483648 is not the max of nothing.
- Mathematically, `NaN` shouldn't be considered a legal value of `polygonalMean`s codomain (`Double`), IEEE be damned.

And I am a bit of a hard-liner when it comes to enforcing `Option` and `Either` use. If it were up to me, `sqrt` would return in an `Option`. That said, I can see why these might be annoying for users.

**Comment by lossyrob** [comment]
@fosskers would you say an appropriate fix for this issue would be to return `Double.NaN` or `NODATA` for instances where we're working on an empty RDD?

**Comment by fosskers** [comment]
From a user's standpoint, `NaN` would be a total surprise, whereas at least `NODATA` is a known value in the world they're working in (their cell type). If `Option` wrapping isn't an option (ha), then `NODATA` (documented!) should suffice.

**Comment by lossyrob** [comment]
NODATA means nothing in the context of a `Double`. `Double.NaN` is our NODATA for Double values, so I think it is similarly appropriate.

**Comment by fosskers** [comment]
Ah I had forgotten that. Yeah, whatever the `NODATA` is per type should be good.
