### ISSUE TITLE
proj4.Transform inconsistency

### ISSUE THREAD

**Issue by kevinmhinson** [geotrellis/geotrellis#1618]
Getting inconsistent results with proj4.Transform when using as a val in fat jar.  Using as a def seems fine.  Defining the same objects in spark-shell instead of importing from jar may be ok.

Test case below repeats the same single lat/lon value 100k times and applies Transform.  Output demonstrates inconsistent results when using val instead of def.  Results are non-deterministic, but in the sample run using as a val, 100k records with the same lat/lon was transformed into 9 different X values, and 2 different Y values.  @lossyrob indicated on gitter it may be a mutability issue.

Screenshots and text versions included below.

screen shot of objects in jar
![from_jar](https://cloud.githubusercontent.com/assets/4745266/18144473/b1194f18-6f7b-11e6-9a8a-ff26e109e8f9.png)

screen shot of use in spark-shell and results
![command_line_and_results](https://cloud.githubusercontent.com/assets/4745266/18144487/be03e9e0-6f7b-11e6-9c3d-783562107eef.png)

text of jar
[from_jar.txt](https://github.com/geotrellis/geotrellis/files/448163/from_jar.txt)

text of command line
[command_line_and_results.txt](https://github.com/geotrellis/geotrellis/files/448165/command_line_and_results.txt)

environment and build.sbt dependencies used
[environment.txt](https://github.com/geotrellis/geotrellis/files/448166/environment.txt)

**Comment by pomadchin** [comment]
As we moved to Spark 2, checked it on Spark 2, locally and on a 5 node cluster, in a spark shell and in tests: 

```scala
import geotrellis.spark._
import geotrellis.proj4.{Transform,LatLng,WebMercator}

object reproj_val {
  val latLon2WebMerc = Transform(LatLng,WebMercator) // (lon,lat) => (x,y)
  val webMerc2LatLon = Transform(WebMercator,LatLng) // (x,y) => (lon,lat)
}
val one_lat_lon = (40.6097839, -111.9690214)
val x10k = Array.fill[(Double, Double)](100000)(one_lat_lon)

val rdd = sc.parallelize(x10k)

rdd.map { case (lat, lon) => reproj_val.latLon2WebMerc(lon, lat) }.map(_._1).countByValue // fine
rdd.map { case (lat, lon) => reproj_val.latLon2WebMerc(lon, lat) }.map(_._2).countByValue // fine
```

So I believe that was caused more by serialization issues => the workaround to use `defs`, or `@transient lazy vals`; though I could not repeat that code behavior on Spark 2 (used kryo serializer). 

@kevinmhinson any thoughts?

**Comment by lossyrob** [comment]
Closing as this seems to be a fixed issue w/ Spark 2.
