### ISSUE TITLE
RDD Slope call returns Tiles of celltype float64 and RDD metadata celltype of float32 

### ISSUE THREAD

**Issue by owcm** [geotrellis/geotrellis#1629]
I loaded a Avro layer consisting of elevation data using HadoopLayerReader. Example code:

```
// Pointer to the Attribute store in HDFS
          val gtTilesFSPath:Path =  new org.apache.hadoop.fs.Path(targetDataStore)
          val conf = SparkUtils.hadoopConfiguration
          val attributeStore = HadoopAttributeStore( gtTilesFSPath, conf)
          val reader: HadoopLayerReader = HadoopLayerReader(gtTilesFSPath)


          val elevRDD: RDD[(SpatialKey, Tile)] with Metadata[TileLayerMetadata[SpatialKey]] =
            reader.query[SpatialKey, Tile, TileLayerMetadata[SpatialKey]](elevLayerId).result
```
Printed out elevRDD metadata celltype was float32 and tiles in RDD had celltype of float32.

Then ran a slope operation:
```
val slopeRDD = elevRDD.slope(1.0)
```

After words looked at RDD's tiles and they had float64 and the slopeRDD metadata indicated float32.  Seems metadata celltype for the RDD should be insync with Tile celltype after focal operations.

**Comment by fosskers** [comment]
Following the yellow brick road, we find:
- [TileLayerRDD.slope](https://github.com/geotrellis/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/mapalgebra/focal/FocalTileRDDMethods.scala#L31) calling `Slope.apply`
- [Slope.apply](https://github.com/geotrellis/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/mapalgebra/focal/Slope.scala#L31) returning a new `Tile` through an operation on the type `SurfacePointCalculation with DoubleArrayTileResult`
- The [resultTile](https://github.com/geotrellis/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/mapalgebra/focal/FocalCalculation.scala#L184) mentioned there being of the type `DoubleArrayTile`
- [DoubleArrayTile](https://github.com/geotrellis/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/DoubleArrayTile.scala#L28) holding an `Array[Double]`

And `Array[Double]` is definitely not `Array[Float]`, as you had expected. The focal operations being done with the more precise `Double` is definitely on purpose, but not converting back to `Float` based on layer metadata may or may not be an oversight. @lossyrob @echeipesh , should `slopeRDD` above have the type:

```scala
RDD[(SpatialKey, DoubleArrayTile)] with Metadata[TileLayerMetadata[SpatialKey]]
```
or
```scala
RDD[(SpatialKey, FloatArrayTile)] with Metadata[TileLayerMetadata[SpatialKey]]
```

**Comment by lossyrob** [comment]
Possibly an issue with other operations, e.g. hillshade
