### ISSUE TITLE
OSM => VectorTiles :: (1) Getting OSM Planet onto HDFS/S3

### ISSUE THREAD

**Issue by fosskers** [geotrellis/geotrellis#1657]
*This is Part 1 of a series of issues documenting the process of creating a world's worth of `VectorTile`s from OSM Planet data. Please use these issues to discuss solutions.*

[This page](http://planet.openstreetmap.org/) offers download links to a 52GB XML file and 33GB Protobuf file that each hold the entire current content of OpenStreepMap's `Element` database.  

**Question:** How does one reliably get that data onto either HDFS or S3, and how is it to be stored there?

**Comment by jnh5y** [comment]
@lossyrob per our conversation in person... here's a link to a GeoMesa PR: https://github.com/locationtech/geomesa/pull/1008

**Comment by fosskers** [comment]
Thansk @jnh5y , that looks to be appropriate for tackling Part 2 (#1658).

**Comment by fosskers** [comment]
This discussion has moved here: https://github.com/geotrellis/vectorpipe/issues/1
