### ISSUE TITLE
OSM => VectorTiles :: (3) RDD[OSMElement] to RDD[Feature[G, D]]

### ISSUE THREAD

**Issue by fosskers** [geotrellis/geotrellis#1659]
*This is Part 3 of a series of issues documenting the process of creating a world's worth of VectorTiles from OSM Planet data. Please use these issues to discuss solutions.*

OSM data has the concepts of `Node`, `Way`, and `Relation`, which don't directly correspond to GeoTrellis geometries.

**Questions:** 

1. What is necessary for such a conversion?
2. What should `D` be?

**Comment by fosskers** [comment]
This isn't a straight mapping. OSM `Way`s are (conceptually) made up of `Node`s, but the XML itself only contains references to those nodes to save on memory. Different Ways can also share Nodes using this "pointer" system. Here is a full node:

```xml
<node id="25496583" lat="51.5173639" lon="-0.140043" version="1" changeset="203496" user="80n" uid="1238" visible="true" timestamp="2007-01-28T11:40:26Z">
  <tag k="highway" v="traffic_signals"/>
</node>
```

And here is a Way. The `ref` attribute corresponds to a `node`'s `id` attribute.
```xml
<way id="5090250" visible="true" timestamp="2009-01-19T19:07:25Z" version="8" changeset="816806" user="Blumpsy" uid="64226">
  <nd ref="822403"/>
  <nd ref="21533912"/>
  <nd ref="821601"/>
  <nd ref="21533910"/>
  <nd ref="135791608"/>
  <nd ref="333725784"/>
  <nd ref="333725781"/>
  <nd ref="333725774"/>
  <nd ref="333725776"/>
  <nd ref="823771"/>
  <tag k="highway" v="residential"/>
  <tag k="name" v="Clipstone Street"/>
  <tag k="oneway" v="yes"/>
</way>
```

**Comment by fosskers** [comment]
Furthermore, Ways correspond to both `Line` and `Polygon` in GeoTrellis. The full analogue to a Polygon is called an `Area`, where its first and last node are the same. In terms of the data structure, however, both are stored as a `Way`.

**Comment by fosskers** [comment]
The `Relation` element might not have an analogue in GeoTrellis.

**Comment by fosskers** [comment]
`D` as `TagMap` seems to be a good fit.

**Comment by lossyrob** [comment]
I think that `Relation` should end up as specific tags in the TagMap, so for all geometries that participate in that relation, they get the relation tags (clearly marked as tags coming from the relation)

**Comment by fosskers** [comment]
I need to find out more how Relations are used in the wild. Some seem to be loose thematic bindings, while others are specific, a la Polygons with holes, etc.

**Comment by fosskers** [comment]
http://wiki.openstreetmap.org/wiki/Types_of_relation#Established_relations

`multipolygon` might be the only one we have to check for explicitly. The others can be relegated to the `TagMap`s of their constituent Elements.

**Comment by fosskers** [comment]
Issue: We need to distinguish between Polys with and without holes. Given: 
```xml
   <member type="way" ref="1" role="inner"/>
   <member type="way" ref="2" role="outer"/>
   <member type="way" ref="3" role="outer"/>
   <member type="way" ref="4" role="inner"/>
```
Without further inspecting of their LatLng, you don't know whether this relation represents:
1. 2 Polys with one hole each
2. 1 Poly made up of two individual `Way`s, with two holes
3.  1 Poly made up of two individual `Way`s, with a single hole made of two `Way`s
4. 1 Poly with two holes, and 1 Poly without
5. 1 Poly with one hole of two Ways, and 1 Poly without
6. ... ? Possibly more permutations?

The permutations obviously increase the more members you add, to a max of 300 members. How does one inspect all these constituent geometries to be able to do a final:

```scala
val polygons: Seq[Polygons] = ???
val lines: Seq[Line] = ???
val smashed: Seq[Polygon] = magic(polygons, lines) // fuses lines into polys, puts holes into parent polys

MultiPolygon(smashed)
```

**Comment by fosskers** [comment]
It might be less of an problem than I had thought; working on it.

**Comment by fosskers** [comment]
This discussion has moved to: https://github.com/geotrellis/vectorpipe/issues/3
