### ISSUE TITLE
`geotrellis-vectortile` wants Spark 1.6.2

### ISSUE THREAD

**Issue by fosskers** [geotrellis/geotrellis#1664]
Quick fix, should be: `"org.apache.spark" %% "spark-core" % Version.spark % "provided"`

**Comment by lossyrob** [comment]
Why does vectortile depend on Spark at all?

**Comment by fosskers** [comment]
Previously it wasn't compiling/assembling without it. I'll revisit it.

**Comment by fosskers** [comment]
@lossyrob It depends on `geotrellis-spark` so that it can write its Avro implicits:

https://github.com/geotrellis/geotrellis/blob/master/vectortile/src/main/scala/geotrellis/vectortile/spark/Implicits.scala

and I recall it needing to depend on `spark-core` as well, or else it wouldn't build. Possibly caused by `spark-core` being `provided` everywhere.

**Comment by lossyrob** [comment]
We should have spark rely on vector tiles, that fits the model better (spark relies on raster and vector). Or have a vector tile spark project.

**Comment by fosskers** [comment]
Unless I make `vectortile` depend on `spark-core` directly, my tests don't compile, docs don't build, and assembly doesn't work.

**Comment by fosskers** [comment]
Moving the Avro codecs to `geotrellis.spark.io.avro` seems best.

**Comment by fosskers** [comment]
Fixed in #1651 .
