### ISSUE TITLE
parseGeoJson does not parse geojson line features with z values

### ISSUE THREAD

**Issue by owcm** [geotrellis/geotrellis#1676]
If a geojson file contains 3D Line or 3D Multiline features and parseGeoJson[JsonFeatureCollection] is called  getAllLines() and getAllMultiLines() returns no feature.   Appears that the z value in the feature definition ex:

{ "type": "LineString", "coordinates": [ [ 332237.636310937232338, 4022332.556734973099083, 3.832781434623091 ], [ 332265.159629545174539, 4022269.875848380383104, 3.837893504002183 ], [ 332285.695189275196753, 4022217.318341301754117, 3.827133549163638 ] ] } },

causes the feature to be skipped.

**Comment by lossyrob** [comment]
https://github.com/geotrellis/geotrellis/blob/master/vector/src/main/scala/geotrellis/vector/io/json/GeometryFormats.scala#L24-L32
