### ISSUE TITLE
Fix spurious HBase failures on Travis

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1680]
e.g. https://travis-ci.org/geotrellis/geotrellis/jobs/168918705

**Comment by pomadchin** [comment]
raw log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/168918705/log.txt

**Comment by pomadchin** [comment]
Caused by protobuf versions mismatch: 

- com.google.protobuf » protobuf-java » 3.0.0 (scalapb)
- com.google.protobuf » protobuf-java » 2.5.0 (hbase)

**Comment by fosskers** [comment]
Does shadowing fix it?

**Comment by pomadchin** [comment]
@fosskers shadowing would work only during assembly builds, think exclusion rule would work O:

**Comment by fosskers** [comment]
Which one are you excluding?
