### ISSUE TITLE
Move Docs to ReadTheDocs

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1682]
We are going to move our markdown documentation to ReadTheDocs.

**Comment by lossyrob** [comment]
This is being tracked by https://github.com/geotrellis/geotrellis-site/pull/49
@fosskers @rossbernet should this be closed?

**Comment by fosskers** [comment]
Perhaps not yet, since we haven't released. Does it being open affect the repo transfer at all?

**Comment by lossyrob** [comment]
No, I'd just like to clear out Docs issues (that won't be done during the RC process) from the 1.0 release project.

**Comment by fosskers** [comment]
This issue probably doesn't need to exist, technically we've already made the move.
