### ISSUE TITLE
Bug in foreachCellByPolygon

### ISSUE THREAD

**Issue by zaikin** [geotrellis/geotrellis#1801]
Hello. I found bug in `foreachCellByPolygon` and added test for my case (https://github.com/geotrellis/geotrellis/pull/1800). But i can not fix it. May be somebody can fix it or give the cue how i can do it?

**Comment by pomadchin** [comment]
Hi @zaikin! Thx for your bug report, we'll have a look into it a bit later today.

**Comment by pomadchin** [comment]
some additional clues: 

expected: 

```
      /*
      ND ND  1
      ND  1  1
      ND ND  1
      */
```

result

```
      /*
      ND ND  1
      ND ND  1
      ND ND  1
      */
```

Pixel is point gives: 

```
      /*
      ND ND  ND
      1     1     1
      ND ND  ND
      */
```

It's an oracle jvm bug / feature only and needs some investigation.

**Comment by zaikin** [comment]
I'm testing only on OpenJDK, i have not OracleJDK.
