### ISSUE TITLE
Allow for adding rasters to the catalog without restarting a running service

### ISSUE THREAD

**Issue by jwalgran** [geotrellis/geotrellis#777]
As I understand it, the catalog is cached when a service is started. Since a catalog is an abstraction, and may not necessarily be a file system directory, that rules out watching for file system changes. The only implementation I can think of would be to refresh the catalog if a request is made for a raster that does not exist, then try again.

**Comment by lossyrob** [comment]
I'm closing this as we are moving away from the Akka engine, and the Spark catalogs already do this.
