### ISSUE TITLE
Revisit combining of tiles in geotrellis-spark

### ISSUE THREAD

**Issue by ameetkini** [geotrellis/geotrellis#807]
Currently, RDDs are partitioned such that a single partition can contain at most one HDFS block of data. This helps optimize operations on RDD in that operations can be map-only. For example, if we do a+b, and both a and b are tiled rasters, then a+b can be a map-only job in Spark - in particular, we don't need a shuffle and reduce simply to resort the tiles back into their respective partitions.

The mechanism that makes this happen is RasterRDD.combineTiles which calls zipPartitions to join the partitions from multiple RDDs. While this is very simple in logic, this can be problematic in the following ways, all of which have a common theme of "RDDs not being partitioned the same way". This may be exacerbated in the future if we make RDD partitioning smarter than it is today (see "Potential changes to the partitioner" below).

1. Combining RDDs of the same number of tiles, but either the number of bands are different or tile sizes are different, either of which end up with RDDs not being partitioned the same way. So we may need to join partition 1 of RDD 1 with partitions 1 and 2 of RDD 2.

2. Combining RDDs of different numbers of tiles. In this case, they are guaranteed to be differently partitioned.

Solution: Write a fancier zipPartitions that can deal with this potential one-to-many relationship. The client logic can then do a "zip" within the partition as it is currenly done in combineTiles. Note that it is one-to-many and not many-to-many because zipPartitions takes an argument the right-hand-side (RHS) RasterRDD and it is that RHS side which will have the "many" side of "one-to-many". This fancier zipPartitions needs to find out for a given partition P or RDD R1, which partitions it joins with from RDD R2. It then needs to issue some RDD operation to read that partition and return it. For this, we can look at how the "lookup" operation figures out which partition to read based on the input argument key.

Potential changes to the partitioner
Today, we estimate the number of tiles that can fit onto a single HDFS block (see RasterSplitGenerator.computeIncrement). This is done crudely using a hard-coded "compression factor" of 30% and tilesPerBlock, which is # of uncompressed tiles that can fit onto a block. This ends up being too pessimistic in most cases, leaving most HDFS blocks around half full.

There are two ways this can be improved:

a. A smarter way to estimate compression factor is to sample the incoming dataset. This can be done in ingest
b. Throw an exception if we end up with partitions that contain more than one
block.
c. remove empty partitions
d. coalesce relatively empty partitions

b,c,d can be done as post-op action, say, coalescePartitions, which is called after any operation that results in a raster on disk. This can be either Ingest, BuildPyramid or any MapAlgebra operation.

Miscellaneous Notes
Currently, BuildPyramid does not write out empty part files (look for if(!partition.isEmpty) ). However, Ingest does write out empty part files. So there is an inconsistency.

**Comment by lossyrob** [comment]
This issue deals with an older version of geotrellis-spark; the joining-without-shuffling issue is mostly solved by using Accumulo to index the tiles according to spatial or spatial-temporal location (as Andy had suggested).
