### ISSUE TITLE
Focal StandardDeviation Benchmark Time-Out

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis#819]
in geotrellis.benchmark.FocalOperationsBenchmark
- timeStandardDeviationSquare1
- timeStandardDeviationSquare3
- timeStandardDeviationCircle1
- timeStandardDeviationCircle2

... all time-out and fail the benchmark. The unit test for SD passes so it's not clear what is going on here.

**Comment by fosskers** [comment]
I'm trying to reproduce this, but with my new project structure as of https://github.com/geotrellis/geotrellis-benchmark/pull/8, many of the benchmarks in `geotrellis-0.10/` throw exceptions:

```
Exception in thread "main" java.lang.RuntimeException: Catalog path /home/colin/code/azavea/geotrellis-benchmark/geotrellis010/src/test/resources/catalog.json does not exist. Please modify your settings.
```
Despite:
```console
colin@yumi ~/c/a/geotrellis-benchmark> find . -name "catalog*"
./geotrellis-0.10/target/scala-2.10/test-classes/catalog.json
./geotrellis-0.10/src/test/resources/catalog.json
./geotrellis/target/scala-2.11/test-classes/catalog.json
./geotrellis/src/test/resources/catalog.json
```

**Comment by fosskers** [comment]
Ah, I see the difference there, `geotrellis010` vs `geotrellis-0.10`. Correcting now.

**Comment by fosskers** [comment]
std deviation benches complete, so this can be closed @lossyrob .
