### ISSUE TITLE
geotrellis.spark.io.hadoop.netCdfRDD more general

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis#904]
Currently this method and the machinery around it is really specific to reading netCDF format that represents multi-band time rasters as used by IPCC. It could be made a lot more generic given enough information about netCDF format. 

Likely there will need to be a `NetCdfConfiguration` defining source fields, which will be used to validate the input and transform functions which will map to desired index.

**Comment by lossyrob** [comment]
Added as part of 82f751d2d2588d9745810059be0073b2e86293ba PR.
