### ISSUE TITLE
geotrellis.spark Catalog features

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#945]
This is an issue to keep track of what features the `geotrellis.spark.io` Catalog architecture should support.

 - [ ] Updating specific tiles in a raster layer.
 - [ ] Deleting a layer
 - [x] Query layer subset by extent

**Comment by pomadchin** [comment]
We have all layer management functions support, so can closed @lossyrob @echeipesh @rossbernet.

**Comment by vsimko** [comment]
Just a question (hopefully related).
Is there a function to delete the whole layer including all zoom levels ?

**Comment by pomadchin** [comment]
@vsimko nope, but it is possible to implement it; you can do the following

```scala
val attributeStore: AccumuloAttributeStore = ???
val layerDeleter: AccumuoLayerDeleter = ???
attributeStore.layerIds.map(layerDeleter.delete)
```

**Comment by vsimko** [comment]
thanks, this is even smaller than my current code

**Comment by pomadchin** [comment]
@vsimko you are always welcome with questions ;) btw you can ask them in our [gitter channel](https://gitter.im/geotrellis/geotrellis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
