### ISSUE TITLE
Handle the "id" field of a GeoJSON Feature.

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#947]
The spec specifies an optional "id" field on Features: http://geojson.org/geojson-spec.html#feature-objects

We need to be able to read these. @echeipesh thoughts?

**Comment by echeipesh** [comment]
It would not be great to have Option[String] on every Feature object. So perhaps there needs to be an API that will return `Seq[Feature[_]], Map[String, Feature[_]]`. The user would be able to use the map to get the correct feature without bloating the object.
