### ISSUE TITLE
Logging in geotrellis-spark

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis#962]
We have inadvertently org.apache.spark.Logging for logging in some places (ex: HadoopCatalog.scala).

This class is tagged with 'DeveloperApi' and following warning:

"DO NOT USE this class outside of Spark. It is intended as an internal utility. This will likely be changed or removed in future releases."

Instead we should use https://github.com/typesafehub/scala-logging. It provides a wrapper around the SLF4J LoggerFactory and some macro magic. Seems simple and good. Latest version compatible with Scala 2.10 is: "com.typesafe" %% "scalalogging-slf4j" % "1.1.0"

Ref: https://github.com/geotrellis/geotrellis/issues/212

**Comment by pomadchin** [comment]
We are using latest `scala-logging`, and in Spark 2 it's not possible to use inbuilt Logging, can be can be closed @lossyrob @echeipesh @rossbernet.
