### ISSUE TITLE
Update benchmarks, move them to benchmarking repository.

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#967]
Move all of our benchmarks (benchmark, vector-benchmark) to https://github.com/geotrellis/benchmark.

Delete the gdal-benchmark project (which is already in the benchmark repo).

**Comment by lossyrob** [comment]
Done, github.com/geotrellis/geotrellis-benchmark

**Comment by ricardobarroslourenco** [comment]
@lossyrob is there any resource that I can reach for metrics/benchmark of geotrellis? We are currently setting up an environment at Banco do Brasil, and this would be highly helpful on defining the cost of our cluster...

**Comment by pomadchin** [comment]
Hi @ricardobarroslourenco, the only up to date bebchmark project we have is https://github.com/locationtech/geotrellis/tree/master/bench

**Comment by ricardobarroslourenco** [comment]
Thanks (again) @pomadchin ! This is for someone when trying to benchmark a certain deployment, correct? I am also looking for measurements, given a certain cluster setup, for comparison. Do you know if anyone has done a study like that, and shared results?

**Comment by pomadchin** [comment]
These are not; These are JMH benchmarks and https://github.com/geotrellis/benchmark are Scaliper benchmarks (similar to JMH). These are relative benchmarks to track regressions in some certain function calls.

For the given cluster comparison it makes not a lot of sense - everything depends too much on the input data, cluster parameters and job configuration at the same time. 

When we introdcue new features we usually make projects like https://github.com/pomadchin/vlm-performance (be carefull it is a bit outdated) to compare new functionality to the old one on the same data set on different cluster configurations.

**Comment by ricardobarroslourenco** [comment]
> For the given cluster comparison it makes not a lot of sense - everything depends too much on the input data, cluster parameters and job configuration at the same time.

I see. The benchmarks are in terms of functionalities introduced, as well as introduced improvements.
But still, how someone dimensions machinery and cluster needs, when aiming to build a new cluster? 

We have gone into a volumetric-based approach (because we are still developing our processing workflow), in a _worst-case_ scenario. For ex.: If I want to process a certain region, I need 10GB of geotiffs, so an ideal case would be a cluster where those would be all in-memory. But there are still a lot of setups that may accommodate this, especially when you aim to do deployment on a public cloud such as AWS, Azure, etc...

**Comment by pomadchin** [comment]
@ricardobarroslourenco I'm afraid I am not aware of such projects. And also not sure that it makes a lot of sense (in general). 

Btw, you're welcome to join our gitter channel (https://gitter.im/geotrellis/geotrellis) so we can try to assist you as much as it is possible. It can be also very interesting to hear a bit more about the problems you solve, mb if there would be a bit more context it would be possible to help you in some more determined fashion?
